/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';

export const getMatchByIdParams = zod.object({
  "id": zod.uuid()
})


export const updateMatchParams = zod.object({
  "id": zod.uuid()
})

export const updateMatchBody = zod.object({
  "foundItemId": zod.uuid(),
  "lostReportId": zod.uuid(),
  "venueId": zod.uuid().optional(),
  "status": zod.enum(['PENDING', 'CONFIRMED', 'REJECTED']),
  "attributeScore": zod.number(),
  "semanticScore": zod.number(),
  "combinedScore": zod.number()
})


export const rejectPublicMatchParams = zod.object({
  "token": zod.string()
})


export const confirmPublicMatchParams = zod.object({
  "token": zod.string()
})


export const getAllMatchesQueryParams = zod.object({
  "foundItem": zod.uuid().optional(),
  "lostItem": zod.uuid().optional(),
  "status": zod.enum(['PENDING', 'CONFIRMED', 'REJECTED']).optional()
})


export const createMatchBody = zod.object({
  "foundItemId": zod.uuid(),
  "lostReportId": zod.uuid(),
  "venueId": zod.uuid().optional(),
  "attributeScore": zod.number(),
  "semanticScore": zod.number(),
  "combinedScore": zod.number()
})


export const createPublicMatchLinkParams = zod.object({
  "id": zod.uuid()
})




export const createPublicMatchLinkBody = zod.object({
  "email": zod.email().min(1)
})


export const getPublicMatchParams = zod.object({
  "token": zod.string()
})


export const getMatchHistogramQueryParams = zod.object({
  "foundItem": zod.uuid().optional(),
  "lostItem": zod.uuid().optional(),
  "status": zod.enum(['PENDING', 'CONFIRMED', 'REJECTED']).optional(),
  "venueId": zod.uuid().optional()
})


export const countMatchesQueryParams = zod.object({
  "foundItem": zod.uuid().optional(),
  "lostItem": zod.uuid().optional(),
  "status": zod.enum(['PENDING', 'CONFIRMED', 'REJECTED']).optional(),
  "venueId": zod.uuid().optional()
})


export const searchBodyQueryMax = 4000;

export const searchBodyKMax = 32;



export const searchBody = zod.object({
  "query": zod.string().min(1).max(searchBodyQueryMax),
  "scope": zod.enum(['LOST', 'FOUND', 'BOTH']).optional(),
  "k": zod.number().min(1).max(searchBodyKMax).optional()
})
