/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';

export const getMatchHistogramQueryParams = zod.object({
  "venueId": zod.uuid().optional(),
  "foundItem": zod.uuid().optional(),
  "lostItem": zod.uuid().optional(),
  "status": zod.string().optional()
})

export const getMatchHistogramResponse = zod.object({
  "perDay": zod.array(zod.object({
  "bucketStart": zod.iso.date().optional(),
  "count": zod.number().optional()
})).optional(),
  "perWeek": zod.array(zod.object({
  "bucketStart": zod.iso.date().optional(),
  "count": zod.number().optional()
})).optional(),
  "perMonth": zod.array(zod.object({
  "bucketStart": zod.iso.date().optional(),
  "count": zod.number().optional()
})).optional()
})


export const countMatchesQueryParams = zod.object({
  "venueId": zod.uuid().optional(),
  "foundItem": zod.uuid().optional(),
  "lostItem": zod.uuid().optional(),
  "status": zod.string().optional()
})

export const countMatchesResponse = zod.object({
  "count": zod.number().optional()
})
