/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CountMatchesStatus } from './countMatchesStatus';

export type CountMatchesParams = {
foundItem?: string;
lostItem?: string;
status?: CountMatchesStatus;
venueId?: string;
};
