/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CountMatchesStatus = typeof CountMatchesStatus[keyof typeof CountMatchesStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CountMatchesStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED',
} as const;
