/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CreateMatchRequest {
  foundItemId: string;
  lostReportId: string;
  venueId?: string;
  attributeScore: number;
  semanticScore: number;
  combinedScore: number;
}
