/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { MatchResponseStatus } from './matchResponseStatus';

export interface MatchResponse {
  id?: string;
  foundItemId?: string;
  lostReportId?: string;
  venueId?: string;
  status?: MatchResponseStatus;
  attributeScore?: number;
  semanticScore?: number;
  combinedScore?: number;
  createdAt?: string;
}
