/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UpdateMatchRequestStatus } from './updateMatchRequestStatus';

export interface UpdateMatchRequest {
  foundItemId: string;
  lostReportId: string;
  venueId?: string;
  status: UpdateMatchRequestStatus;
  attributeScore: number;
  semanticScore: number;
  combinedScore: number;
}
