/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';

export const getUserByIdParams = zod.object({
  "id": zod.uuid()
})


export const updateUserParams = zod.object({
  "id": zod.uuid()
})




export const updateUserBody = zod.object({
  "email": zod.email().min(1),
  "role": zod.enum(['STAFF', 'OPS_MANAGER', 'ADMIN'])
})



export const createUserBodyPasswordMin = 8;
export const createUserBodyPasswordMax = 2147483647;



export const createUserBody = zod.object({
  "email": zod.email().min(1),
  "role": zod.enum(['STAFF', 'OPS_MANAGER', 'ADMIN']),
  "password": zod.string().min(createUserBodyPasswordMin).max(createUserBodyPasswordMax)
})


export const getUserByEmailQueryParams = zod.object({
  "email": zod.string()
})
