/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ItemSearchRequest,
  ItemSearchResponse
} from '.././model';

import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType } from '../../mutator/custom-instance';




export const search = (
    itemSearchRequest: ItemSearchRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ItemSearchResponse>(
      {url: `/api/matches/search`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: itemSearchRequest, signal
    },
      );
    }
  


export const getSearchMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof search>>, TError,{data: ItemSearchRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof search>>, TError,{data: ItemSearchRequest}, TContext> => {

const mutationKey = ['search'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof search>>, {data: ItemSearchRequest}> = (props) => {
          const {data} = props ?? {};

          return  search(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SearchMutationResult = NonNullable<Awaited<ReturnType<typeof search>>>
    export type SearchMutationBody = ItemSearchRequest
    export type SearchMutationError = ErrorType<unknown>

    export const useSearch = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof search>>, TError,{data: ItemSearchRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof search>>,
        TError,
        {data: ItemSearchRequest},
        TContext
      > => {

      const mutationOptions = getSearchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    