/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreatePickupRequest,
  CreatePickupScheduleRequest,
  GetPickupsParams,
  GetSchedulesParams,
  PickupResponse,
  PickupScheduleResponse,
  PickupSlotResponse,
  PublicPickupResponse,
  StaffPickupRequest,
  UpdatePickupRequest,
  UpdatePickupScheduleRequest
} from '.././model';

import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType } from '../../mutator/custom-instance';




export const updatePickup = (
    pickupId: string,
    staffPickupRequest: StaffPickupRequest,
 ) => {
      
      
      return customInstance<PickupResponse>(
      {url: `/api/pickups/${pickupId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: staffPickupRequest
    },
      );
    }
  


export const getUpdatePickupMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePickup>>, TError,{pickupId: string;data: StaffPickupRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updatePickup>>, TError,{pickupId: string;data: StaffPickupRequest}, TContext> => {

const mutationKey = ['updatePickup'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePickup>>, {pickupId: string;data: StaffPickupRequest}> = (props) => {
          const {pickupId,data} = props ?? {};

          return  updatePickup(pickupId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePickupMutationResult = NonNullable<Awaited<ReturnType<typeof updatePickup>>>
    export type UpdatePickupMutationBody = StaffPickupRequest
    export type UpdatePickupMutationError = ErrorType<unknown>

    export const useUpdatePickup = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePickup>>, TError,{pickupId: string;data: StaffPickupRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePickup>>,
        TError,
        {pickupId: string;data: StaffPickupRequest},
        TContext
      > => {

      const mutationOptions = getUpdatePickupMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deletePickup = (
    pickupId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/pickups/${pickupId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeletePickupMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePickup>>, TError,{pickupId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deletePickup>>, TError,{pickupId: string}, TContext> => {

const mutationKey = ['deletePickup'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePickup>>, {pickupId: string}> = (props) => {
          const {pickupId} = props ?? {};

          return  deletePickup(pickupId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeletePickupMutationResult = NonNullable<Awaited<ReturnType<typeof deletePickup>>>
    
    export type DeletePickupMutationError = ErrorType<unknown>

    export const useDeletePickup = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePickup>>, TError,{pickupId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePickup>>,
        TError,
        {pickupId: string},
        TContext
      > => {

      const mutationOptions = getDeletePickupMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const updateSchedule = (
    scheduleId: string,
    updatePickupScheduleRequest: UpdatePickupScheduleRequest,
 ) => {
      
      
      return customInstance<PickupScheduleResponse>(
      {url: `/api/pickups/schedule/${scheduleId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updatePickupScheduleRequest
    },
      );
    }
  


export const getUpdateScheduleMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSchedule>>, TError,{scheduleId: string;data: UpdatePickupScheduleRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateSchedule>>, TError,{scheduleId: string;data: UpdatePickupScheduleRequest}, TContext> => {

const mutationKey = ['updateSchedule'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSchedule>>, {scheduleId: string;data: UpdatePickupScheduleRequest}> = (props) => {
          const {scheduleId,data} = props ?? {};

          return  updateSchedule(scheduleId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateScheduleMutationResult = NonNullable<Awaited<ReturnType<typeof updateSchedule>>>
    export type UpdateScheduleMutationBody = UpdatePickupScheduleRequest
    export type UpdateScheduleMutationError = ErrorType<unknown>

    export const useUpdateSchedule = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSchedule>>, TError,{scheduleId: string;data: UpdatePickupScheduleRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSchedule>>,
        TError,
        {scheduleId: string;data: UpdatePickupScheduleRequest},
        TContext
      > => {

      const mutationOptions = getUpdateScheduleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteSchedule = (
    scheduleId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/pickups/schedule/${scheduleId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteScheduleMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSchedule>>, TError,{scheduleId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteSchedule>>, TError,{scheduleId: string}, TContext> => {

const mutationKey = ['deleteSchedule'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSchedule>>, {scheduleId: string}> = (props) => {
          const {scheduleId} = props ?? {};

          return  deleteSchedule(scheduleId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteScheduleMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSchedule>>>
    
    export type DeleteScheduleMutationError = ErrorType<unknown>

    export const useDeleteSchedule = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSchedule>>, TError,{scheduleId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteSchedule>>,
        TError,
        {scheduleId: string},
        TContext
      > => {

      const mutationOptions = getDeleteScheduleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getPublicSlots = (
    token: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PickupSlotResponse[]>(
      {url: `/api/pickups/public/${token}`, method: 'GET', signal
    },
      );
    }
  



export const getGetPublicSlotsQueryKey = (token?: string,) => {
    return [
    `/api/pickups/public/${token}`
    ] as const;
    }

    
export const getGetPublicSlotsQueryOptions = <TData = Awaited<ReturnType<typeof getPublicSlots>>, TError = ErrorType<unknown>>(token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicSlots>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPublicSlotsQueryKey(token);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPublicSlots>>> = ({ signal }) => getPublicSlots(token, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(token), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPublicSlots>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetPublicSlotsQueryResult = NonNullable<Awaited<ReturnType<typeof getPublicSlots>>>
export type GetPublicSlotsQueryError = ErrorType<unknown>


export function useGetPublicSlots<TData = Awaited<ReturnType<typeof getPublicSlots>>, TError = ErrorType<unknown>>(
 token: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicSlots>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPublicSlots>>,
          TError,
          Awaited<ReturnType<typeof getPublicSlots>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPublicSlots<TData = Awaited<ReturnType<typeof getPublicSlots>>, TError = ErrorType<unknown>>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicSlots>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPublicSlots>>,
          TError,
          Awaited<ReturnType<typeof getPublicSlots>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPublicSlots<TData = Awaited<ReturnType<typeof getPublicSlots>>, TError = ErrorType<unknown>>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicSlots>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetPublicSlots<TData = Awaited<ReturnType<typeof getPublicSlots>>, TError = ErrorType<unknown>>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicSlots>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetPublicSlotsQueryOptions(token,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updatePublicPickup = (
    token: string,
    updatePickupRequest: UpdatePickupRequest,
 ) => {
      
      
      return customInstance<PublicPickupResponse>(
      {url: `/api/pickups/public/${token}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updatePickupRequest
    },
      );
    }
  


export const getUpdatePublicPickupMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePublicPickup>>, TError,{token: string;data: UpdatePickupRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updatePublicPickup>>, TError,{token: string;data: UpdatePickupRequest}, TContext> => {

const mutationKey = ['updatePublicPickup'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePublicPickup>>, {token: string;data: UpdatePickupRequest}> = (props) => {
          const {token,data} = props ?? {};

          return  updatePublicPickup(token,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePublicPickupMutationResult = NonNullable<Awaited<ReturnType<typeof updatePublicPickup>>>
    export type UpdatePublicPickupMutationBody = UpdatePickupRequest
    export type UpdatePublicPickupMutationError = ErrorType<unknown>

    export const useUpdatePublicPickup = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePublicPickup>>, TError,{token: string;data: UpdatePickupRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePublicPickup>>,
        TError,
        {token: string;data: UpdatePickupRequest},
        TContext
      > => {

      const mutationOptions = getUpdatePublicPickupMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const createPublicPickup = (
    token: string,
    createPickupRequest: CreatePickupRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PublicPickupResponse>(
      {url: `/api/pickups/public/${token}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPickupRequest, signal
    },
      );
    }
  


export const getCreatePublicPickupMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPublicPickup>>, TError,{token: string;data: CreatePickupRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createPublicPickup>>, TError,{token: string;data: CreatePickupRequest}, TContext> => {

const mutationKey = ['createPublicPickup'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPublicPickup>>, {token: string;data: CreatePickupRequest}> = (props) => {
          const {token,data} = props ?? {};

          return  createPublicPickup(token,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePublicPickupMutationResult = NonNullable<Awaited<ReturnType<typeof createPublicPickup>>>
    export type CreatePublicPickupMutationBody = CreatePickupRequest
    export type CreatePublicPickupMutationError = ErrorType<unknown>

    export const useCreatePublicPickup = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPublicPickup>>, TError,{token: string;data: CreatePickupRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPublicPickup>>,
        TError,
        {token: string;data: CreatePickupRequest},
        TContext
      > => {

      const mutationOptions = getCreatePublicPickupMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deletePublicPickup = (
    token: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/pickups/public/${token}`, method: 'DELETE'
    },
      );
    }
  


export const getDeletePublicPickupMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePublicPickup>>, TError,{token: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deletePublicPickup>>, TError,{token: string}, TContext> => {

const mutationKey = ['deletePublicPickup'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePublicPickup>>, {token: string}> = (props) => {
          const {token} = props ?? {};

          return  deletePublicPickup(token,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeletePublicPickupMutationResult = NonNullable<Awaited<ReturnType<typeof deletePublicPickup>>>
    
    export type DeletePublicPickupMutationError = ErrorType<unknown>

    export const useDeletePublicPickup = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePublicPickup>>, TError,{token: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePublicPickup>>,
        TError,
        {token: string},
        TContext
      > => {

      const mutationOptions = getDeletePublicPickupMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const upsertPickupForMatch = (
    matchId: string,
    staffPickupRequest: StaffPickupRequest,
 ) => {
      
      
      return customInstance<PickupResponse>(
      {url: `/api/pickups/matches/${matchId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: staffPickupRequest
    },
      );
    }
  


export const getUpsertPickupForMatchMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertPickupForMatch>>, TError,{matchId: string;data: StaffPickupRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof upsertPickupForMatch>>, TError,{matchId: string;data: StaffPickupRequest}, TContext> => {

const mutationKey = ['upsertPickupForMatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof upsertPickupForMatch>>, {matchId: string;data: StaffPickupRequest}> = (props) => {
          const {matchId,data} = props ?? {};

          return  upsertPickupForMatch(matchId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpsertPickupForMatchMutationResult = NonNullable<Awaited<ReturnType<typeof upsertPickupForMatch>>>
    export type UpsertPickupForMatchMutationBody = StaffPickupRequest
    export type UpsertPickupForMatchMutationError = ErrorType<unknown>

    export const useUpsertPickupForMatch = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertPickupForMatch>>, TError,{matchId: string;data: StaffPickupRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof upsertPickupForMatch>>,
        TError,
        {matchId: string;data: StaffPickupRequest},
        TContext
      > => {

      const mutationOptions = getUpsertPickupForMatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deletePickupForMatch = (
    matchId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/pickups/matches/${matchId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeletePickupForMatchMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePickupForMatch>>, TError,{matchId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deletePickupForMatch>>, TError,{matchId: string}, TContext> => {

const mutationKey = ['deletePickupForMatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePickupForMatch>>, {matchId: string}> = (props) => {
          const {matchId} = props ?? {};

          return  deletePickupForMatch(matchId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeletePickupForMatchMutationResult = NonNullable<Awaited<ReturnType<typeof deletePickupForMatch>>>
    
    export type DeletePickupForMatchMutationError = ErrorType<unknown>

    export const useDeletePickupForMatch = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePickupForMatch>>, TError,{matchId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePickupForMatch>>,
        TError,
        {matchId: string},
        TContext
      > => {

      const mutationOptions = getDeletePickupForMatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getSchedules = (
    params?: GetSchedulesParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PickupScheduleResponse[]>(
      {url: `/api/pickups/schedule`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetSchedulesQueryKey = (params?: GetSchedulesParams,) => {
    return [
    `/api/pickups/schedule`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetSchedulesQueryOptions = <TData = Awaited<ReturnType<typeof getSchedules>>, TError = ErrorType<unknown>>(params?: GetSchedulesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedules>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSchedulesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSchedules>>> = ({ signal }) => getSchedules(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSchedules>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetSchedulesQueryResult = NonNullable<Awaited<ReturnType<typeof getSchedules>>>
export type GetSchedulesQueryError = ErrorType<unknown>


export function useGetSchedules<TData = Awaited<ReturnType<typeof getSchedules>>, TError = ErrorType<unknown>>(
 params: undefined |  GetSchedulesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedules>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSchedules>>,
          TError,
          Awaited<ReturnType<typeof getSchedules>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetSchedules<TData = Awaited<ReturnType<typeof getSchedules>>, TError = ErrorType<unknown>>(
 params?: GetSchedulesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedules>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSchedules>>,
          TError,
          Awaited<ReturnType<typeof getSchedules>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetSchedules<TData = Awaited<ReturnType<typeof getSchedules>>, TError = ErrorType<unknown>>(
 params?: GetSchedulesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedules>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetSchedules<TData = Awaited<ReturnType<typeof getSchedules>>, TError = ErrorType<unknown>>(
 params?: GetSchedulesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedules>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetSchedulesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const createSchedule = (
    createPickupScheduleRequest: CreatePickupScheduleRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PickupScheduleResponse>(
      {url: `/api/pickups/schedule`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPickupScheduleRequest, signal
    },
      );
    }
  


export const getCreateScheduleMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSchedule>>, TError,{data: CreatePickupScheduleRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createSchedule>>, TError,{data: CreatePickupScheduleRequest}, TContext> => {

const mutationKey = ['createSchedule'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSchedule>>, {data: CreatePickupScheduleRequest}> = (props) => {
          const {data} = props ?? {};

          return  createSchedule(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateScheduleMutationResult = NonNullable<Awaited<ReturnType<typeof createSchedule>>>
    export type CreateScheduleMutationBody = CreatePickupScheduleRequest
    export type CreateScheduleMutationError = ErrorType<unknown>

    export const useCreateSchedule = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSchedule>>, TError,{data: CreatePickupScheduleRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createSchedule>>,
        TError,
        {data: CreatePickupScheduleRequest},
        TContext
      > => {

      const mutationOptions = getCreateScheduleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getPickups = (
    params?: GetPickupsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PickupResponse[]>(
      {url: `/api/pickups`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetPickupsQueryKey = (params?: GetPickupsParams,) => {
    return [
    `/api/pickups`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetPickupsQueryOptions = <TData = Awaited<ReturnType<typeof getPickups>>, TError = ErrorType<unknown>>(params?: GetPickupsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPickups>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPickupsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPickups>>> = ({ signal }) => getPickups(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPickups>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetPickupsQueryResult = NonNullable<Awaited<ReturnType<typeof getPickups>>>
export type GetPickupsQueryError = ErrorType<unknown>


export function useGetPickups<TData = Awaited<ReturnType<typeof getPickups>>, TError = ErrorType<unknown>>(
 params: undefined |  GetPickupsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPickups>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPickups>>,
          TError,
          Awaited<ReturnType<typeof getPickups>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPickups<TData = Awaited<ReturnType<typeof getPickups>>, TError = ErrorType<unknown>>(
 params?: GetPickupsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPickups>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPickups>>,
          TError,
          Awaited<ReturnType<typeof getPickups>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPickups<TData = Awaited<ReturnType<typeof getPickups>>, TError = ErrorType<unknown>>(
 params?: GetPickupsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPickups>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetPickups<TData = Awaited<ReturnType<typeof getPickups>>, TError = ErrorType<unknown>>(
 params?: GetPickupsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPickups>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetPickupsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




