/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateLostReportRequest,
  LostReportResponse,
  UpdateLostReportRequest
} from '.././model';

import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType } from '../../mutator/custom-instance';




export const getLostReportById = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<LostReportResponse>(
      {url: `/api/lost-reports/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetLostReportByIdQueryKey = (id?: string,) => {
    return [
    `/api/lost-reports/${id}`
    ] as const;
    }

    
export const getGetLostReportByIdQueryOptions = <TData = Awaited<ReturnType<typeof getLostReportById>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLostReportByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLostReportById>>> = ({ signal }) => getLostReportById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLostReportById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetLostReportByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getLostReportById>>>
export type GetLostReportByIdQueryError = ErrorType<unknown>


export function useGetLostReportById<TData = Awaited<ReturnType<typeof getLostReportById>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportById>>,
          TError,
          Awaited<ReturnType<typeof getLostReportById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportById<TData = Awaited<ReturnType<typeof getLostReportById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportById>>,
          TError,
          Awaited<ReturnType<typeof getLostReportById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportById<TData = Awaited<ReturnType<typeof getLostReportById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetLostReportById<TData = Awaited<ReturnType<typeof getLostReportById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetLostReportByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateLostReport = (
    id: string,
    updateLostReportRequest: UpdateLostReportRequest,
 ) => {
      
      
      return customInstance<LostReportResponse>(
      {url: `/api/lost-reports/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateLostReportRequest
    },
      );
    }
  


export const getUpdateLostReportMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLostReport>>, TError,{id: string;data: UpdateLostReportRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateLostReport>>, TError,{id: string;data: UpdateLostReportRequest}, TContext> => {

const mutationKey = ['updateLostReport'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateLostReport>>, {id: string;data: UpdateLostReportRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateLostReport(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateLostReportMutationResult = NonNullable<Awaited<ReturnType<typeof updateLostReport>>>
    export type UpdateLostReportMutationBody = UpdateLostReportRequest
    export type UpdateLostReportMutationError = ErrorType<unknown>

    export const useUpdateLostReport = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLostReport>>, TError,{id: string;data: UpdateLostReportRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateLostReport>>,
        TError,
        {id: string;data: UpdateLostReportRequest},
        TContext
      > => {

      const mutationOptions = getUpdateLostReportMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAllLostReports = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<LostReportResponse[]>(
      {url: `/api/lost-reports`, method: 'GET', signal
    },
      );
    }
  



export const getGetAllLostReportsQueryKey = () => {
    return [
    `/api/lost-reports`
    ] as const;
    }

    
export const getGetAllLostReportsQueryOptions = <TData = Awaited<ReturnType<typeof getAllLostReports>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllLostReportsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllLostReports>>> = ({ signal }) => getAllLostReports(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAllLostReportsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllLostReports>>>
export type GetAllLostReportsQueryError = ErrorType<unknown>


export function useGetAllLostReports<TData = Awaited<ReturnType<typeof getAllLostReports>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllLostReports>>,
          TError,
          Awaited<ReturnType<typeof getAllLostReports>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllLostReports<TData = Awaited<ReturnType<typeof getAllLostReports>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllLostReports>>,
          TError,
          Awaited<ReturnType<typeof getAllLostReports>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllLostReports<TData = Awaited<ReturnType<typeof getAllLostReports>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAllLostReports<TData = Awaited<ReturnType<typeof getAllLostReports>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAllLostReportsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const createLostReport = (
    createLostReportRequest: CreateLostReportRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<LostReportResponse>(
      {url: `/api/lost-reports`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createLostReportRequest, signal
    },
      );
    }
  


export const getCreateLostReportMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLostReport>>, TError,{data: CreateLostReportRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createLostReport>>, TError,{data: CreateLostReportRequest}, TContext> => {

const mutationKey = ['createLostReport'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createLostReport>>, {data: CreateLostReportRequest}> = (props) => {
          const {data} = props ?? {};

          return  createLostReport(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateLostReportMutationResult = NonNullable<Awaited<ReturnType<typeof createLostReport>>>
    export type CreateLostReportMutationBody = CreateLostReportRequest
    export type CreateLostReportMutationError = ErrorType<unknown>

    export const useCreateLostReport = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLostReport>>, TError,{data: CreateLostReportRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createLostReport>>,
        TError,
        {data: CreateLostReportRequest},
        TContext
      > => {

      const mutationOptions = getCreateLostReportMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    