/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CountLostReports1Params,
  CountLostReportsParams,
  CountResponse,
  CreateLostReportRequest,
  GetAllLostReports1Params,
  GetAllLostReportsParams,
  GetLostReportHistogram1Params,
  GetLostReportHistogramParams,
  HistogramResponse,
  LostReportResponse,
  UpdateLostReportRequest
} from '.././model';

import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType } from '../../mutator/custom-instance';




export const getLostReportById = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<LostReportResponse>(
      {url: `/api/lost-reports/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetLostReportByIdQueryKey = (id?: string,) => {
    return [
    `/api/lost-reports/${id}`
    ] as const;
    }

    
export const getGetLostReportByIdQueryOptions = <TData = Awaited<ReturnType<typeof getLostReportById>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLostReportByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLostReportById>>> = ({ signal }) => getLostReportById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLostReportById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetLostReportByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getLostReportById>>>
export type GetLostReportByIdQueryError = ErrorType<unknown>


export function useGetLostReportById<TData = Awaited<ReturnType<typeof getLostReportById>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportById>>,
          TError,
          Awaited<ReturnType<typeof getLostReportById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportById<TData = Awaited<ReturnType<typeof getLostReportById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportById>>,
          TError,
          Awaited<ReturnType<typeof getLostReportById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportById<TData = Awaited<ReturnType<typeof getLostReportById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetLostReportById<TData = Awaited<ReturnType<typeof getLostReportById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetLostReportByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateLostReport = (
    id: string,
    updateLostReportRequest: UpdateLostReportRequest,
 ) => {
      
      
      return customInstance<LostReportResponse>(
      {url: `/api/lost-reports/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateLostReportRequest
    },
      );
    }
  


export const getUpdateLostReportMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLostReport>>, TError,{id: string;data: UpdateLostReportRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateLostReport>>, TError,{id: string;data: UpdateLostReportRequest}, TContext> => {

const mutationKey = ['updateLostReport'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateLostReport>>, {id: string;data: UpdateLostReportRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateLostReport(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateLostReportMutationResult = NonNullable<Awaited<ReturnType<typeof updateLostReport>>>
    export type UpdateLostReportMutationBody = UpdateLostReportRequest
    export type UpdateLostReportMutationError = ErrorType<unknown>

    export const useUpdateLostReport = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLostReport>>, TError,{id: string;data: UpdateLostReportRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateLostReport>>,
        TError,
        {id: string;data: UpdateLostReportRequest},
        TContext
      > => {

      const mutationOptions = getUpdateLostReportMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getLostReportById1 = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<LostReportResponse>(
      {url: `/api/lost-items/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetLostReportById1QueryKey = (id?: string,) => {
    return [
    `/api/lost-items/${id}`
    ] as const;
    }

    
export const getGetLostReportById1QueryOptions = <TData = Awaited<ReturnType<typeof getLostReportById1>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLostReportById1QueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLostReportById1>>> = ({ signal }) => getLostReportById1(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLostReportById1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetLostReportById1QueryResult = NonNullable<Awaited<ReturnType<typeof getLostReportById1>>>
export type GetLostReportById1QueryError = ErrorType<unknown>


export function useGetLostReportById1<TData = Awaited<ReturnType<typeof getLostReportById1>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportById1>>,
          TError,
          Awaited<ReturnType<typeof getLostReportById1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportById1<TData = Awaited<ReturnType<typeof getLostReportById1>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportById1>>,
          TError,
          Awaited<ReturnType<typeof getLostReportById1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportById1<TData = Awaited<ReturnType<typeof getLostReportById1>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetLostReportById1<TData = Awaited<ReturnType<typeof getLostReportById1>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById1>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetLostReportById1QueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateLostReport1 = (
    id: string,
    updateLostReportRequest: UpdateLostReportRequest,
 ) => {
      
      
      return customInstance<LostReportResponse>(
      {url: `/api/lost-items/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateLostReportRequest
    },
      );
    }
  


export const getUpdateLostReport1MutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLostReport1>>, TError,{id: string;data: UpdateLostReportRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateLostReport1>>, TError,{id: string;data: UpdateLostReportRequest}, TContext> => {

const mutationKey = ['updateLostReport1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateLostReport1>>, {id: string;data: UpdateLostReportRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateLostReport1(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateLostReport1MutationResult = NonNullable<Awaited<ReturnType<typeof updateLostReport1>>>
    export type UpdateLostReport1MutationBody = UpdateLostReportRequest
    export type UpdateLostReport1MutationError = ErrorType<unknown>

    export const useUpdateLostReport1 = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLostReport1>>, TError,{id: string;data: UpdateLostReportRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateLostReport1>>,
        TError,
        {id: string;data: UpdateLostReportRequest},
        TContext
      > => {

      const mutationOptions = getUpdateLostReport1MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAllLostReports = (
    params?: GetAllLostReportsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<LostReportResponse[]>(
      {url: `/api/lost-items`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetAllLostReportsQueryKey = (params?: GetAllLostReportsParams,) => {
    return [
    `/api/lost-items`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllLostReportsQueryOptions = <TData = Awaited<ReturnType<typeof getAllLostReports>>, TError = ErrorType<unknown>>(params?: GetAllLostReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllLostReportsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllLostReports>>> = ({ signal }) => getAllLostReports(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAllLostReportsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllLostReports>>>
export type GetAllLostReportsQueryError = ErrorType<unknown>


export function useGetAllLostReports<TData = Awaited<ReturnType<typeof getAllLostReports>>, TError = ErrorType<unknown>>(
 params: undefined |  GetAllLostReportsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllLostReports>>,
          TError,
          Awaited<ReturnType<typeof getAllLostReports>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllLostReports<TData = Awaited<ReturnType<typeof getAllLostReports>>, TError = ErrorType<unknown>>(
 params?: GetAllLostReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllLostReports>>,
          TError,
          Awaited<ReturnType<typeof getAllLostReports>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllLostReports<TData = Awaited<ReturnType<typeof getAllLostReports>>, TError = ErrorType<unknown>>(
 params?: GetAllLostReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAllLostReports<TData = Awaited<ReturnType<typeof getAllLostReports>>, TError = ErrorType<unknown>>(
 params?: GetAllLostReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAllLostReportsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const createLostReport = (
    createLostReportRequest: CreateLostReportRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<LostReportResponse>(
      {url: `/api/lost-items`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createLostReportRequest, signal
    },
      );
    }
  


export const getCreateLostReportMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLostReport>>, TError,{data: CreateLostReportRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createLostReport>>, TError,{data: CreateLostReportRequest}, TContext> => {

const mutationKey = ['createLostReport'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createLostReport>>, {data: CreateLostReportRequest}> = (props) => {
          const {data} = props ?? {};

          return  createLostReport(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateLostReportMutationResult = NonNullable<Awaited<ReturnType<typeof createLostReport>>>
    export type CreateLostReportMutationBody = CreateLostReportRequest
    export type CreateLostReportMutationError = ErrorType<unknown>

    export const useCreateLostReport = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLostReport>>, TError,{data: CreateLostReportRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createLostReport>>,
        TError,
        {data: CreateLostReportRequest},
        TContext
      > => {

      const mutationOptions = getCreateLostReportMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAllLostReports1 = (
    params?: GetAllLostReports1Params,
 signal?: AbortSignal
) => {
      
      
      return customInstance<LostReportResponse[]>(
      {url: `/api/lost-reports`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetAllLostReports1QueryKey = (params?: GetAllLostReports1Params,) => {
    return [
    `/api/lost-reports`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllLostReports1QueryOptions = <TData = Awaited<ReturnType<typeof getAllLostReports1>>, TError = ErrorType<unknown>>(params?: GetAllLostReports1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllLostReports1QueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllLostReports1>>> = ({ signal }) => getAllLostReports1(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAllLostReports1QueryResult = NonNullable<Awaited<ReturnType<typeof getAllLostReports1>>>
export type GetAllLostReports1QueryError = ErrorType<unknown>


export function useGetAllLostReports1<TData = Awaited<ReturnType<typeof getAllLostReports1>>, TError = ErrorType<unknown>>(
 params: undefined |  GetAllLostReports1Params, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllLostReports1>>,
          TError,
          Awaited<ReturnType<typeof getAllLostReports1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllLostReports1<TData = Awaited<ReturnType<typeof getAllLostReports1>>, TError = ErrorType<unknown>>(
 params?: GetAllLostReports1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllLostReports1>>,
          TError,
          Awaited<ReturnType<typeof getAllLostReports1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllLostReports1<TData = Awaited<ReturnType<typeof getAllLostReports1>>, TError = ErrorType<unknown>>(
 params?: GetAllLostReports1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAllLostReports1<TData = Awaited<ReturnType<typeof getAllLostReports1>>, TError = ErrorType<unknown>>(
 params?: GetAllLostReports1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports1>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAllLostReports1QueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const createLostReport1 = (
    createLostReportRequest: CreateLostReportRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<LostReportResponse>(
      {url: `/api/lost-reports`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createLostReportRequest, signal
    },
      );
    }
  


export const getCreateLostReport1MutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLostReport1>>, TError,{data: CreateLostReportRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createLostReport1>>, TError,{data: CreateLostReportRequest}, TContext> => {

const mutationKey = ['createLostReport1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createLostReport1>>, {data: CreateLostReportRequest}> = (props) => {
          const {data} = props ?? {};

          return  createLostReport1(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateLostReport1MutationResult = NonNullable<Awaited<ReturnType<typeof createLostReport1>>>
    export type CreateLostReport1MutationBody = CreateLostReportRequest
    export type CreateLostReport1MutationError = ErrorType<unknown>

    export const useCreateLostReport1 = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLostReport1>>, TError,{data: CreateLostReportRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createLostReport1>>,
        TError,
        {data: CreateLostReportRequest},
        TContext
      > => {

      const mutationOptions = getCreateLostReport1MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getLostReportHistogram = (
    params?: GetLostReportHistogramParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<HistogramResponse>(
      {url: `/api/lost-items/histogram`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetLostReportHistogramQueryKey = (params?: GetLostReportHistogramParams,) => {
    return [
    `/api/lost-items/histogram`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetLostReportHistogramQueryOptions = <TData = Awaited<ReturnType<typeof getLostReportHistogram>>, TError = ErrorType<unknown>>(params?: GetLostReportHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLostReportHistogramQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLostReportHistogram>>> = ({ signal }) => getLostReportHistogram(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetLostReportHistogramQueryResult = NonNullable<Awaited<ReturnType<typeof getLostReportHistogram>>>
export type GetLostReportHistogramQueryError = ErrorType<unknown>


export function useGetLostReportHistogram<TData = Awaited<ReturnType<typeof getLostReportHistogram>>, TError = ErrorType<unknown>>(
 params: undefined |  GetLostReportHistogramParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportHistogram>>,
          TError,
          Awaited<ReturnType<typeof getLostReportHistogram>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportHistogram<TData = Awaited<ReturnType<typeof getLostReportHistogram>>, TError = ErrorType<unknown>>(
 params?: GetLostReportHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportHistogram>>,
          TError,
          Awaited<ReturnType<typeof getLostReportHistogram>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportHistogram<TData = Awaited<ReturnType<typeof getLostReportHistogram>>, TError = ErrorType<unknown>>(
 params?: GetLostReportHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetLostReportHistogram<TData = Awaited<ReturnType<typeof getLostReportHistogram>>, TError = ErrorType<unknown>>(
 params?: GetLostReportHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetLostReportHistogramQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getLostReportHistogram1 = (
    params?: GetLostReportHistogram1Params,
 signal?: AbortSignal
) => {
      
      
      return customInstance<HistogramResponse>(
      {url: `/api/lost-reports/histogram`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetLostReportHistogram1QueryKey = (params?: GetLostReportHistogram1Params,) => {
    return [
    `/api/lost-reports/histogram`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetLostReportHistogram1QueryOptions = <TData = Awaited<ReturnType<typeof getLostReportHistogram1>>, TError = ErrorType<unknown>>(params?: GetLostReportHistogram1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLostReportHistogram1QueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLostReportHistogram1>>> = ({ signal }) => getLostReportHistogram1(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetLostReportHistogram1QueryResult = NonNullable<Awaited<ReturnType<typeof getLostReportHistogram1>>>
export type GetLostReportHistogram1QueryError = ErrorType<unknown>


export function useGetLostReportHistogram1<TData = Awaited<ReturnType<typeof getLostReportHistogram1>>, TError = ErrorType<unknown>>(
 params: undefined |  GetLostReportHistogram1Params, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportHistogram1>>,
          TError,
          Awaited<ReturnType<typeof getLostReportHistogram1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportHistogram1<TData = Awaited<ReturnType<typeof getLostReportHistogram1>>, TError = ErrorType<unknown>>(
 params?: GetLostReportHistogram1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportHistogram1>>,
          TError,
          Awaited<ReturnType<typeof getLostReportHistogram1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportHistogram1<TData = Awaited<ReturnType<typeof getLostReportHistogram1>>, TError = ErrorType<unknown>>(
 params?: GetLostReportHistogram1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetLostReportHistogram1<TData = Awaited<ReturnType<typeof getLostReportHistogram1>>, TError = ErrorType<unknown>>(
 params?: GetLostReportHistogram1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram1>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetLostReportHistogram1QueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const countLostReports = (
    params?: CountLostReportsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CountResponse>(
      {url: `/api/lost-items/count`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getCountLostReportsQueryKey = (params?: CountLostReportsParams,) => {
    return [
    `/api/lost-items/count`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getCountLostReportsQueryOptions = <TData = Awaited<ReturnType<typeof countLostReports>>, TError = ErrorType<unknown>>(params?: CountLostReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countLostReports>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCountLostReportsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof countLostReports>>> = ({ signal }) => countLostReports(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof countLostReports>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type CountLostReportsQueryResult = NonNullable<Awaited<ReturnType<typeof countLostReports>>>
export type CountLostReportsQueryError = ErrorType<unknown>


export function useCountLostReports<TData = Awaited<ReturnType<typeof countLostReports>>, TError = ErrorType<unknown>>(
 params: undefined |  CountLostReportsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof countLostReports>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof countLostReports>>,
          TError,
          Awaited<ReturnType<typeof countLostReports>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useCountLostReports<TData = Awaited<ReturnType<typeof countLostReports>>, TError = ErrorType<unknown>>(
 params?: CountLostReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countLostReports>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof countLostReports>>,
          TError,
          Awaited<ReturnType<typeof countLostReports>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useCountLostReports<TData = Awaited<ReturnType<typeof countLostReports>>, TError = ErrorType<unknown>>(
 params?: CountLostReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countLostReports>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useCountLostReports<TData = Awaited<ReturnType<typeof countLostReports>>, TError = ErrorType<unknown>>(
 params?: CountLostReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countLostReports>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getCountLostReportsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const countLostReports1 = (
    params?: CountLostReports1Params,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CountResponse>(
      {url: `/api/lost-reports/count`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getCountLostReports1QueryKey = (params?: CountLostReports1Params,) => {
    return [
    `/api/lost-reports/count`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getCountLostReports1QueryOptions = <TData = Awaited<ReturnType<typeof countLostReports1>>, TError = ErrorType<unknown>>(params?: CountLostReports1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countLostReports1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCountLostReports1QueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof countLostReports1>>> = ({ signal }) => countLostReports1(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof countLostReports1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type CountLostReports1QueryResult = NonNullable<Awaited<ReturnType<typeof countLostReports1>>>
export type CountLostReports1QueryError = ErrorType<unknown>


export function useCountLostReports1<TData = Awaited<ReturnType<typeof countLostReports1>>, TError = ErrorType<unknown>>(
 params: undefined |  CountLostReports1Params, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof countLostReports1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof countLostReports1>>,
          TError,
          Awaited<ReturnType<typeof countLostReports1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useCountLostReports1<TData = Awaited<ReturnType<typeof countLostReports1>>, TError = ErrorType<unknown>>(
 params?: CountLostReports1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countLostReports1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof countLostReports1>>,
          TError,
          Awaited<ReturnType<typeof countLostReports1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useCountLostReports1<TData = Awaited<ReturnType<typeof countLostReports1>>, TError = ErrorType<unknown>>(
 params?: CountLostReports1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countLostReports1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useCountLostReports1<TData = Awaited<ReturnType<typeof countLostReports1>>, TError = ErrorType<unknown>>(
 params?: CountLostReports1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countLostReports1>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getCountLostReports1QueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




