/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';

export const getLostReportByIdParams = zod.object({
  "id": zod.uuid()
})


export const updateLostReportParams = zod.object({
  "id": zod.uuid()
})





export const updateLostReportBody = zod.object({
  "photoKey": zod.string().optional(),
  "description": zod.string().min(1),
  "lostAt": zod.iso.datetime({}),
  "location": zod.string().optional(),
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']),
  "contactEmail": zod.email().min(1),
  "attributes": zod.object({
  "category": zod.string().optional(),
  "brand": zod.string().optional(),
  "color": zod.string().optional(),
  "marks": zod.array(zod.string()).optional()
}).optional()
})






export const createLostReportBody = zod.object({
  "photoKey": zod.string().optional(),
  "description": zod.string().min(1),
  "lostAt": zod.iso.datetime({}),
  "location": zod.string().optional(),
  "contactEmail": zod.email().min(1),
  "attributes": zod.object({
  "category": zod.string().optional(),
  "brand": zod.string().optional(),
  "color": zod.string().optional(),
  "marks": zod.array(zod.string()).optional()
}).optional()
})
