/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';

export const getLostReportByIdParams = zod.object({
  "id": zod.uuid()
})


export const updateLostReportParams = zod.object({
  "id": zod.uuid()
})





export const updateLostReportBody = zod.object({
  "description": zod.string().min(1),
  "lostAt": zod.iso.datetime({}),
  "location": zod.string().optional(),
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']),
  "venueId": zod.uuid().optional(),
  "contactEmail": zod.email().min(1),
  "attributes": zod.object({
  "category": zod.string().optional(),
  "description": zod.string().optional(),
  "brand": zod.string().optional(),
  "color": zod.string().optional(),
  "marks": zod.array(zod.string()).optional()
}).optional()
})


export const deleteLostReportParams = zod.object({
  "id": zod.uuid()
})


export const getLostReportPhotoParams = zod.object({
  "id": zod.uuid()
})


export const updateLostReportPhotoParams = zod.object({
  "id": zod.uuid()
})

export const updateLostReportPhotoBody = zod.object({
  "photo": zod.instanceof(File)
})


export const getAllLostReportsQueryParams = zod.object({
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']).optional()
})


export const createLostReportBodyDescriptionMin = 0;
export const createLostReportBodyDescriptionMax = 2000;

export const createLostReportBodyLocationMin = 0;
export const createLostReportBodyLocationMax = 255;

export const createLostReportBodyContactEmailMin = 0;
export const createLostReportBodyContactEmailMax = 255;



export const createLostReportBody = zod.object({
  "description": zod.string().min(createLostReportBodyDescriptionMin).max(createLostReportBodyDescriptionMax),
  "lostAt": zod.iso.datetime({}),
  "location": zod.string().min(createLostReportBodyLocationMin).max(createLostReportBodyLocationMax).optional(),
  "venueId": zod.uuid().optional(),
  "contactEmail": zod.email().min(createLostReportBodyContactEmailMin).max(createLostReportBodyContactEmailMax),
  "attributes": zod.object({
  "category": zod.string().optional(),
  "description": zod.string().optional(),
  "brand": zod.string().optional(),
  "color": zod.string().optional(),
  "marks": zod.array(zod.string()).optional()
}).optional()
})


export const getLostReportPhotoUrlParams = zod.object({
  "id": zod.uuid()
})


export const getLostReportHistogramQueryParams = zod.object({
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']).optional(),
  "venueId": zod.uuid().optional()
})


export const countLostReportsQueryParams = zod.object({
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']).optional(),
  "venueId": zod.uuid().optional()
})
