/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';

export const getLostReportByIdParams = zod.object({
  "id": zod.uuid()
})


export const updateLostReportParams = zod.object({
  "id": zod.uuid()
})





export const updateLostReportBody = zod.object({
  "photoKey": zod.string().optional(),
  "description": zod.string().min(1),
  "lostAt": zod.iso.datetime({}),
  "location": zod.string().optional(),
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']),
  "venueId": zod.uuid().optional(),
  "contactEmail": zod.email().min(1),
  "attributes": zod.object({
  "category": zod.string().optional(),
  "brand": zod.string().optional(),
  "color": zod.string().optional(),
  "marks": zod.array(zod.string()).optional()
}).optional()
})


export const getLostReportById1Params = zod.object({
  "id": zod.uuid()
})


export const updateLostReport1Params = zod.object({
  "id": zod.uuid()
})





export const updateLostReport1Body = zod.object({
  "photoKey": zod.string().optional(),
  "description": zod.string().min(1),
  "lostAt": zod.iso.datetime({}),
  "location": zod.string().optional(),
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']),
  "venueId": zod.uuid().optional(),
  "contactEmail": zod.email().min(1),
  "attributes": zod.object({
  "category": zod.string().optional(),
  "brand": zod.string().optional(),
  "color": zod.string().optional(),
  "marks": zod.array(zod.string()).optional()
}).optional()
})


export const getAllLostReportsQueryParams = zod.object({
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']).optional()
})


export const createLostReportBodyPhotoKeyMin = 0;
export const createLostReportBodyPhotoKeyMax = 255;

export const createLostReportBodyDescriptionMin = 0;
export const createLostReportBodyDescriptionMax = 2000;

export const createLostReportBodyLocationMin = 0;
export const createLostReportBodyLocationMax = 255;

export const createLostReportBodyContactEmailMin = 0;
export const createLostReportBodyContactEmailMax = 255;



export const createLostReportBody = zod.object({
  "photoKey": zod.string().min(createLostReportBodyPhotoKeyMin).max(createLostReportBodyPhotoKeyMax).optional(),
  "description": zod.string().min(createLostReportBodyDescriptionMin).max(createLostReportBodyDescriptionMax),
  "lostAt": zod.iso.datetime({}),
  "location": zod.string().min(createLostReportBodyLocationMin).max(createLostReportBodyLocationMax).optional(),
  "venueId": zod.uuid().optional(),
  "contactEmail": zod.email().min(createLostReportBodyContactEmailMin).max(createLostReportBodyContactEmailMax),
  "attributes": zod.object({
  "category": zod.string().optional(),
  "brand": zod.string().optional(),
  "color": zod.string().optional(),
  "marks": zod.array(zod.string()).optional()
}).optional()
})


export const getAllLostReports1QueryParams = zod.object({
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']).optional()
})


export const createLostReport1BodyPhotoKeyMin = 0;
export const createLostReport1BodyPhotoKeyMax = 255;

export const createLostReport1BodyDescriptionMin = 0;
export const createLostReport1BodyDescriptionMax = 2000;

export const createLostReport1BodyLocationMin = 0;
export const createLostReport1BodyLocationMax = 255;

export const createLostReport1BodyContactEmailMin = 0;
export const createLostReport1BodyContactEmailMax = 255;



export const createLostReport1Body = zod.object({
  "photoKey": zod.string().min(createLostReport1BodyPhotoKeyMin).max(createLostReport1BodyPhotoKeyMax).optional(),
  "description": zod.string().min(createLostReport1BodyDescriptionMin).max(createLostReport1BodyDescriptionMax),
  "lostAt": zod.iso.datetime({}),
  "location": zod.string().min(createLostReport1BodyLocationMin).max(createLostReport1BodyLocationMax).optional(),
  "venueId": zod.uuid().optional(),
  "contactEmail": zod.email().min(createLostReport1BodyContactEmailMin).max(createLostReport1BodyContactEmailMax),
  "attributes": zod.object({
  "category": zod.string().optional(),
  "brand": zod.string().optional(),
  "color": zod.string().optional(),
  "marks": zod.array(zod.string()).optional()
}).optional()
})


export const getLostReportHistogramQueryParams = zod.object({
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']).optional(),
  "venueId": zod.uuid().optional()
})


export const getLostReportHistogram1QueryParams = zod.object({
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']).optional(),
  "venueId": zod.uuid().optional()
})


export const countLostReportsQueryParams = zod.object({
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']).optional(),
  "venueId": zod.uuid().optional()
})


export const countLostReports1QueryParams = zod.object({
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']).optional(),
  "venueId": zod.uuid().optional()
})
