/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface NotificationBlueprintResponse {
  id?: string;
  name?: string;
  language?: string;
  subject?: string;
  header?: string;
  body?: string;
}
