/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UpdateNotificationRequest {
  matchId: string;
  venueId?: string;
  /** @minLength 1 */
  recipientAddress: string;
  /** @minLength 1 */
  language: string;
  /** @minLength 1 */
  subject: string;
  /** @minLength 1 */
  header: string;
  /** @minLength 1 */
  body: string;
  sentAt?: string;
}
