/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  VenueKpiResponse,
  VenueResponse
} from '.././model';

import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType } from '../../mutator/custom-instance';




export const getAllVenues = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<VenueResponse[]>(
      {url: `/api/venues`, method: 'GET', signal
    },
      );
    }
  



export const getGetAllVenuesQueryKey = () => {
    return [
    `/api/venues`
    ] as const;
    }

    
export const getGetAllVenuesQueryOptions = <TData = Awaited<ReturnType<typeof getAllVenues>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllVenues>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllVenuesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllVenues>>> = ({ signal }) => getAllVenues(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllVenues>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAllVenuesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllVenues>>>
export type GetAllVenuesQueryError = ErrorType<unknown>


export function useGetAllVenues<TData = Awaited<ReturnType<typeof getAllVenues>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllVenues>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllVenues>>,
          TError,
          Awaited<ReturnType<typeof getAllVenues>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllVenues<TData = Awaited<ReturnType<typeof getAllVenues>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllVenues>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllVenues>>,
          TError,
          Awaited<ReturnType<typeof getAllVenues>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllVenues<TData = Awaited<ReturnType<typeof getAllVenues>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllVenues>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAllVenues<TData = Awaited<ReturnType<typeof getAllVenues>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllVenues>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAllVenuesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getVenueById = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<VenueResponse>(
      {url: `/api/venues/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetVenueByIdQueryKey = (id?: string,) => {
    return [
    `/api/venues/${id}`
    ] as const;
    }

    
export const getGetVenueByIdQueryOptions = <TData = Awaited<ReturnType<typeof getVenueById>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVenueById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVenueByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVenueById>>> = ({ signal }) => getVenueById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVenueById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetVenueByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getVenueById>>>
export type GetVenueByIdQueryError = ErrorType<unknown>


export function useGetVenueById<TData = Awaited<ReturnType<typeof getVenueById>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVenueById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVenueById>>,
          TError,
          Awaited<ReturnType<typeof getVenueById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetVenueById<TData = Awaited<ReturnType<typeof getVenueById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVenueById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVenueById>>,
          TError,
          Awaited<ReturnType<typeof getVenueById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetVenueById<TData = Awaited<ReturnType<typeof getVenueById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVenueById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetVenueById<TData = Awaited<ReturnType<typeof getVenueById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVenueById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetVenueByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getVenueKpis = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<VenueKpiResponse>(
      {url: `/api/venues/kpis`, method: 'GET', signal
    },
      );
    }
  



export const getGetVenueKpisQueryKey = () => {
    return [
    `/api/venues/kpis`
    ] as const;
    }

    
export const getGetVenueKpisQueryOptions = <TData = Awaited<ReturnType<typeof getVenueKpis>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVenueKpis>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVenueKpisQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVenueKpis>>> = ({ signal }) => getVenueKpis(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVenueKpis>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetVenueKpisQueryResult = NonNullable<Awaited<ReturnType<typeof getVenueKpis>>>
export type GetVenueKpisQueryError = ErrorType<unknown>


export function useGetVenueKpis<TData = Awaited<ReturnType<typeof getVenueKpis>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVenueKpis>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVenueKpis>>,
          TError,
          Awaited<ReturnType<typeof getVenueKpis>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetVenueKpis<TData = Awaited<ReturnType<typeof getVenueKpis>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVenueKpis>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVenueKpis>>,
          TError,
          Awaited<ReturnType<typeof getVenueKpis>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetVenueKpis<TData = Awaited<ReturnType<typeof getVenueKpis>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVenueKpis>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetVenueKpis<TData = Awaited<ReturnType<typeof getVenueKpis>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVenueKpis>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetVenueKpisQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getVenueKpisById = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<VenueKpiResponse>(
      {url: `/api/venues/kpis/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetVenueKpisByIdQueryKey = (id?: string,) => {
    return [
    `/api/venues/kpis/${id}`
    ] as const;
    }

    
export const getGetVenueKpisByIdQueryOptions = <TData = Awaited<ReturnType<typeof getVenueKpisById>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVenueKpisById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVenueKpisByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVenueKpisById>>> = ({ signal }) => getVenueKpisById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVenueKpisById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetVenueKpisByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getVenueKpisById>>>
export type GetVenueKpisByIdQueryError = ErrorType<unknown>


export function useGetVenueKpisById<TData = Awaited<ReturnType<typeof getVenueKpisById>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVenueKpisById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVenueKpisById>>,
          TError,
          Awaited<ReturnType<typeof getVenueKpisById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetVenueKpisById<TData = Awaited<ReturnType<typeof getVenueKpisById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVenueKpisById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVenueKpisById>>,
          TError,
          Awaited<ReturnType<typeof getVenueKpisById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetVenueKpisById<TData = Awaited<ReturnType<typeof getVenueKpisById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVenueKpisById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetVenueKpisById<TData = Awaited<ReturnType<typeof getVenueKpisById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVenueKpisById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetVenueKpisByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




