/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';

export const getAllVenuesResponseItem = zod.object({
  "id": zod.uuid().optional(),
  "name": zod.string().optional(),
  "tone": zod.string().optional(),
  "defaultLanguage": zod.string().optional()
})
export const getAllVenuesResponse = zod.array(getAllVenuesResponseItem)


export const getVenueByIdParams = zod.object({
  "id": zod.uuid()
})

export const getVenueByIdResponse = zod.object({
  "id": zod.uuid().optional(),
  "name": zod.string().optional(),
  "tone": zod.string().optional(),
  "defaultLanguage": zod.string().optional()
})


export const getVenueKpisResponse = zod.object({
  "venueId": zod.uuid().optional(),
  "totalFoundItems": zod.number().optional(),
  "totalLostItems": zod.number().optional(),
  "totalMatches": zod.number().optional(),
  "pendingMatches": zod.number().optional()
})


export const getVenueKpisByIdParams = zod.object({
  "id": zod.uuid()
})

export const getVenueKpisByIdResponse = zod.object({
  "venueId": zod.uuid().optional(),
  "totalFoundItems": zod.number().optional(),
  "totalLostItems": zod.number().optional(),
  "totalMatches": zod.number().optional(),
  "pendingMatches": zod.number().optional()
})
