{{- if .Values.loki.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "foundflow.labels" . | nindent 4 }}
    app.kubernetes.io/name: loki
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.global.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.loki.storageSize }}
{{- end }}
