/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';

export const getLostReportPhotoParams = zod.object({
  "id": zod.uuid()
})


export const updateLostReportPhotoParams = zod.object({
  "id": zod.uuid()
})

export const updateLostReportPhotoBody = zod.object({
  "photo": zod.instanceof(File)
})


export const getLostReportPhoto1Params = zod.object({
  "id": zod.uuid()
})


export const updateLostReportPhoto1Params = zod.object({
  "id": zod.uuid()
})

export const updateLostReportPhoto1Body = zod.object({
  "photo": zod.instanceof(File)
})


export const getLostReportByIdParams = zod.object({
  "id": zod.uuid()
})


export const updateLostReportParams = zod.object({
  "id": zod.uuid()
})





export const updateLostReportBody = zod.object({
  "description": zod.string().min(1),
  "lostAt": zod.iso.datetime({}),
  "location": zod.string().optional(),
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']),
  "venueId": zod.uuid().optional(),
  "contactEmail": zod.email().min(1),
  "attributes": zod.object({
  "category": zod.string().optional(),
  "brand": zod.string().optional(),
  "color": zod.string().optional(),
  "marks": zod.array(zod.string()).optional()
}).optional()
})


export const getLostReportById1Params = zod.object({
  "id": zod.uuid()
})


export const updateLostReport1Params = zod.object({
  "id": zod.uuid()
})





export const updateLostReport1Body = zod.object({
  "description": zod.string().min(1),
  "lostAt": zod.iso.datetime({}),
  "location": zod.string().optional(),
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']),
  "venueId": zod.uuid().optional(),
  "contactEmail": zod.email().min(1),
  "attributes": zod.object({
  "category": zod.string().optional(),
  "brand": zod.string().optional(),
  "color": zod.string().optional(),
  "marks": zod.array(zod.string()).optional()
}).optional()
})


export const getAllLostReportsQueryParams = zod.object({
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']).optional()
})


export const createLostReportWithPhotoBodyRequestDescriptionMin = 0;
export const createLostReportWithPhotoBodyRequestDescriptionMax = 2000;

export const createLostReportWithPhotoBodyRequestLocationMin = 0;
export const createLostReportWithPhotoBodyRequestLocationMax = 255;

export const createLostReportWithPhotoBodyRequestContactEmailMin = 0;
export const createLostReportWithPhotoBodyRequestContactEmailMax = 255;



export const createLostReportWithPhotoBody = zod.object({
  "request": zod.object({
  "description": zod.string().min(createLostReportWithPhotoBodyRequestDescriptionMin).max(createLostReportWithPhotoBodyRequestDescriptionMax),
  "lostAt": zod.iso.datetime({}),
  "location": zod.string().min(createLostReportWithPhotoBodyRequestLocationMin).max(createLostReportWithPhotoBodyRequestLocationMax).optional(),
  "venueId": zod.uuid().optional(),
  "contactEmail": zod.email().min(createLostReportWithPhotoBodyRequestContactEmailMin).max(createLostReportWithPhotoBodyRequestContactEmailMax),
  "attributes": zod.object({
  "category": zod.string().optional(),
  "brand": zod.string().optional(),
  "color": zod.string().optional(),
  "marks": zod.array(zod.string()).optional()
}).optional()
}),
  "photo": zod.instanceof(File).optional()
})


export const getAllLostReports1QueryParams = zod.object({
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']).optional()
})


export const createLostReportWithPhoto1BodyRequestDescriptionMin = 0;
export const createLostReportWithPhoto1BodyRequestDescriptionMax = 2000;

export const createLostReportWithPhoto1BodyRequestLocationMin = 0;
export const createLostReportWithPhoto1BodyRequestLocationMax = 255;

export const createLostReportWithPhoto1BodyRequestContactEmailMin = 0;
export const createLostReportWithPhoto1BodyRequestContactEmailMax = 255;



export const createLostReportWithPhoto1Body = zod.object({
  "request": zod.object({
  "description": zod.string().min(createLostReportWithPhoto1BodyRequestDescriptionMin).max(createLostReportWithPhoto1BodyRequestDescriptionMax),
  "lostAt": zod.iso.datetime({}),
  "location": zod.string().min(createLostReportWithPhoto1BodyRequestLocationMin).max(createLostReportWithPhoto1BodyRequestLocationMax).optional(),
  "venueId": zod.uuid().optional(),
  "contactEmail": zod.email().min(createLostReportWithPhoto1BodyRequestContactEmailMin).max(createLostReportWithPhoto1BodyRequestContactEmailMax),
  "attributes": zod.object({
  "category": zod.string().optional(),
  "brand": zod.string().optional(),
  "color": zod.string().optional(),
  "marks": zod.array(zod.string()).optional()
}).optional()
}),
  "photo": zod.instanceof(File).optional()
})


export const getLostReportPhotoUrlParams = zod.object({
  "id": zod.uuid()
})


export const getLostReportPhotoUrl1Params = zod.object({
  "id": zod.uuid()
})


export const getLostReportHistogramQueryParams = zod.object({
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']).optional(),
  "venueId": zod.uuid().optional()
})


export const getLostReportHistogram1QueryParams = zod.object({
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']).optional(),
  "venueId": zod.uuid().optional()
})


export const countLostReportsQueryParams = zod.object({
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']).optional(),
  "venueId": zod.uuid().optional()
})


export const countLostReports1QueryParams = zod.object({
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']).optional(),
  "venueId": zod.uuid().optional()
})
