/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';

export const getLostReportPhotoParams = zod.object({
  "id": zod.uuid()
})


export const updateLostReportPhotoParams = zod.object({
  "id": zod.uuid()
})

export const updateLostReportPhotoBody = zod.object({
  "photo": zod.instanceof(File)
})


export const getLostReportPhoto1Params = zod.object({
  "id": zod.uuid()
})


export const updateLostReportPhoto1Params = zod.object({
  "id": zod.uuid()
})

export const updateLostReportPhoto1Body = zod.object({
  "photo": zod.instanceof(File)
})


export const getLostReportByIdParams = zod.object({
  "id": zod.uuid()
})


export const updateLostReportParams = zod.object({
  "id": zod.uuid()
})





export const updateLostReportBody = zod.object({
  "description": zod.string().min(1),
  "lostAt": zod.iso.datetime({}),
  "location": zod.string().optional(),
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']),
  "venueId": zod.uuid().optional(),
  "contactEmail": zod.email().min(1),
  "attributes": zod.object({
  "category": zod.string().optional(),
  "brand": zod.string().optional(),
  "color": zod.string().optional(),
  "marks": zod.array(zod.string()).optional()
}).optional()
})


export const getLostReportById1Params = zod.object({
  "id": zod.uuid()
})


export const updateLostReport1Params = zod.object({
  "id": zod.uuid()
})





export const updateLostReport1Body = zod.object({
  "description": zod.string().min(1),
  "lostAt": zod.iso.datetime({}),
  "location": zod.string().optional(),
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']),
  "venueId": zod.uuid().optional(),
  "contactEmail": zod.email().min(1),
  "attributes": zod.object({
  "category": zod.string().optional(),
  "brand": zod.string().optional(),
  "color": zod.string().optional(),
  "marks": zod.array(zod.string()).optional()
}).optional()
})


export const getAllLostReportsQueryParams = zod.object({
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']).optional()
})


export const createLostReportWithPhotoBodyDescriptionMin = 0;
export const createLostReportWithPhotoBodyDescriptionMax = 2000;

export const createLostReportWithPhotoBodyLocationMin = 0;
export const createLostReportWithPhotoBodyLocationMax = 255;

export const createLostReportWithPhotoBodyContactEmailMin = 0;
export const createLostReportWithPhotoBodyContactEmailMax = 255;



export const createLostReportWithPhotoBody = zod.object({
  "description": zod.string().min(createLostReportWithPhotoBodyDescriptionMin).max(createLostReportWithPhotoBodyDescriptionMax),
  "lostAt": zod.iso.datetime({}),
  "location": zod.string().min(createLostReportWithPhotoBodyLocationMin).max(createLostReportWithPhotoBodyLocationMax).optional(),
  "venueId": zod.uuid().optional(),
  "contactEmail": zod.email().min(createLostReportWithPhotoBodyContactEmailMin).max(createLostReportWithPhotoBodyContactEmailMax),
  "attributes": zod.object({
  "category": zod.string().optional(),
  "brand": zod.string().optional(),
  "color": zod.string().optional(),
  "marks": zod.array(zod.string()).optional()
}).optional()
})


export const getAllLostReports1QueryParams = zod.object({
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']).optional()
})


export const createLostReportWithPhoto1BodyDescriptionMin = 0;
export const createLostReportWithPhoto1BodyDescriptionMax = 2000;

export const createLostReportWithPhoto1BodyLocationMin = 0;
export const createLostReportWithPhoto1BodyLocationMax = 255;

export const createLostReportWithPhoto1BodyContactEmailMin = 0;
export const createLostReportWithPhoto1BodyContactEmailMax = 255;



export const createLostReportWithPhoto1Body = zod.object({
  "description": zod.string().min(createLostReportWithPhoto1BodyDescriptionMin).max(createLostReportWithPhoto1BodyDescriptionMax),
  "lostAt": zod.iso.datetime({}),
  "location": zod.string().min(createLostReportWithPhoto1BodyLocationMin).max(createLostReportWithPhoto1BodyLocationMax).optional(),
  "venueId": zod.uuid().optional(),
  "contactEmail": zod.email().min(createLostReportWithPhoto1BodyContactEmailMin).max(createLostReportWithPhoto1BodyContactEmailMax),
  "attributes": zod.object({
  "category": zod.string().optional(),
  "brand": zod.string().optional(),
  "color": zod.string().optional(),
  "marks": zod.array(zod.string()).optional()
}).optional()
})


export const getLostReportPhotoUrlParams = zod.object({
  "id": zod.uuid()
})


export const getLostReportPhotoUrl1Params = zod.object({
  "id": zod.uuid()
})


export const getLostReportHistogramQueryParams = zod.object({
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']).optional(),
  "venueId": zod.uuid().optional()
})


export const getLostReportHistogram1QueryParams = zod.object({
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']).optional(),
  "venueId": zod.uuid().optional()
})


export const countLostReportsQueryParams = zod.object({
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']).optional(),
  "venueId": zod.uuid().optional()
})


export const countLostReports1QueryParams = zod.object({
  "status": zod.enum(['OPEN', 'MATCHED', 'CLOSED', 'COLLECTED']).optional(),
  "venueId": zod.uuid().optional()
})
