/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetAllMatchesStatus = typeof GetAllMatchesStatus[keyof typeof GetAllMatchesStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAllMatchesStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED',
} as const;
