/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetMatchHistogramStatus = typeof GetMatchHistogramStatus[keyof typeof GetMatchHistogramStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetMatchHistogramStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED',
} as const;
