/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { GetMatchHistogramStatus } from './getMatchHistogramStatus';

export type GetMatchHistogramParams = {
foundItem?: string;
lostItem?: string;
status?: GetMatchHistogramStatus;
venueId?: string;
};
