/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TimeBucketCount } from './timeBucketCount';

export interface HistogramResponse {
  perDay?: TimeBucketCount[];
  perWeek?: TimeBucketCount[];
  perMonth?: TimeBucketCount[];
}
