/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SearchResultItem } from './searchResultItem';

export interface ItemSearchResponse {
  answer?: string;
  grounded?: boolean;
  citations?: string[];
  results?: SearchResultItem[];
}
