/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ItemSearchRequestScope } from './itemSearchRequestScope';

export interface ItemSearchRequest {
  /**
   * @minLength 0
   * @maxLength 4000
   */
  query: string;
  scope?: ItemSearchRequestScope;
  /**
   * @minimum 1
   * @maximum 32
   */
  k?: number;
}
