/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ItemSearchRequestScope = typeof ItemSearchRequestScope[keyof typeof ItemSearchRequestScope];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ItemSearchRequestScope = {
  LOST: 'LOST',
  FOUND: 'FOUND',
  BOTH: 'BOTH',
} as const;
