/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ItemAttributesPayload {
  category?: string;
  description?: string;
  brand?: string;
  color?: string;
  marks?: string[];
}
