/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type MatchResponseStatus = typeof MatchResponseStatus[keyof typeof MatchResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MatchResponseStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED',
} as const;
