/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ItemAttributesPayload } from './itemAttributesPayload';

export interface PublicFoundItemResponse {
  id?: string;
  description?: string;
  foundAt?: string;
  locationHint?: string;
  status?: string;
  attributes?: ItemAttributesPayload;
  photoUrl?: string;
}
