/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type SearchResultItemItemType = typeof SearchResultItemItemType[keyof typeof SearchResultItemItemType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SearchResultItemItemType = {
  LOST: 'LOST',
  FOUND: 'FOUND',
} as const;
