/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UpdateMatchRequestStatus = typeof UpdateMatchRequestStatus[keyof typeof UpdateMatchRequestStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateMatchRequestStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED',
} as const;
