/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';

export const updatePickupParams = zod.object({
  "pickupId": zod.uuid()
})




export const updatePickupBody = zod.object({
  "pickupAt": zod.iso.datetime({}),
  "venueId": zod.uuid().optional(),
  "matchId": zod.uuid().optional(),
  "email": zod.email().min(1)
})


export const deletePickupParams = zod.object({
  "pickupId": zod.uuid()
})


export const updateScheduleParams = zod.object({
  "scheduleId": zod.uuid()
})




export const updateScheduleBody = zod.object({
  "recurrenceType": zod.enum(['ONCE', 'WEEKLY']).optional(),
  "startDate": zod.iso.date(),
  "endDate": zod.iso.date().optional(),
  "dayOfWeek": zod.enum(['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY']).optional(),
  "startTime": zod.string(),
  "endTime": zod.string(),
  "slotLengthInMinutes": zod.number().min(1).optional(),
  "venueId": zod.uuid().optional()
})


export const deleteScheduleParams = zod.object({
  "scheduleId": zod.uuid()
})


export const getPublicSlotsParams = zod.object({
  "token": zod.string()
})


export const updatePublicPickupParams = zod.object({
  "token": zod.string()
})




export const updatePublicPickupBody = zod.object({
  "pickupAt": zod.iso.datetime({}),
  "email": zod.email().min(1)
})


export const createPublicPickupParams = zod.object({
  "token": zod.string()
})




export const createPublicPickupBody = zod.object({
  "pickupAt": zod.iso.datetime({}),
  "email": zod.email().min(1)
})


export const deletePublicPickupParams = zod.object({
  "token": zod.string()
})


export const upsertPickupForMatchParams = zod.object({
  "matchId": zod.uuid()
})




export const upsertPickupForMatchBody = zod.object({
  "pickupAt": zod.iso.datetime({}),
  "venueId": zod.uuid().optional(),
  "matchId": zod.uuid().optional(),
  "email": zod.email().min(1)
})


export const deletePickupForMatchParams = zod.object({
  "matchId": zod.uuid()
})


export const getSchedulesQueryParams = zod.object({
  "venueId": zod.uuid().optional()
})





export const createScheduleBody = zod.object({
  "recurrenceType": zod.enum(['ONCE', 'WEEKLY']).optional(),
  "startDate": zod.iso.date(),
  "endDate": zod.iso.date().optional(),
  "dayOfWeek": zod.enum(['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY']).optional(),
  "startTime": zod.string(),
  "endTime": zod.string(),
  "slotLengthInMinutes": zod.number().min(1).optional(),
  "venueId": zod.uuid().optional()
})


export const getPickupsQueryParams = zod.object({
  "venueId": zod.uuid().optional()
})
