/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';

export const getFoundItemByIdParams = zod.object({
  "id": zod.uuid()
})


export const updateFoundItemParams = zod.object({
  "id": zod.uuid()
})

export const updateFoundItemBody = zod.object({
  "description": zod.string().optional(),
  "foundAt": zod.iso.datetime({}),
  "locationHint": zod.string().optional(),
  "status": zod.enum(['STORED', 'RESERVED', 'RETURNED', 'DISPOSED']),
  "venueId": zod.uuid(),
  "reporterId": zod.uuid(),
  "attributes": zod.object({
  "category": zod.string().optional(),
  "brand": zod.string().optional(),
  "color": zod.string().optional(),
  "marks": zod.array(zod.string()).optional()
}).optional()
})


export const deleteFoundItemParams = zod.object({
  "id": zod.uuid()
})


export const getFoundItemPhotoParams = zod.object({
  "id": zod.uuid()
})


export const updateFoundItemPhotoParams = zod.object({
  "id": zod.uuid()
})

export const updateFoundItemPhotoBody = zod.object({
  "photo": zod.instanceof(File)
})


export const getAllFoundItemsQueryParams = zod.object({
  "status": zod.enum(['STORED', 'RESERVED', 'RETURNED', 'DISPOSED']).optional()
})


export const createFoundItemWithPhotoBody = zod.object({
  "request": zod.object({
  "description": zod.string().optional(),
  "foundAt": zod.iso.datetime({}),
  "locationHint": zod.string().optional(),
  "venueId": zod.uuid(),
  "reporterId": zod.uuid(),
  "attributes": zod.object({
  "category": zod.string().optional(),
  "brand": zod.string().optional(),
  "color": zod.string().optional(),
  "marks": zod.array(zod.string()).optional()
}).optional()
}),
  "photo": zod.instanceof(File)
})


export const getFoundItemPhotoUrlParams = zod.object({
  "id": zod.uuid()
})


export const getFoundItemHistogramQueryParams = zod.object({
  "status": zod.enum(['STORED', 'RESERVED', 'RETURNED', 'DISPOSED']).optional(),
  "venueId": zod.uuid().optional()
})


export const countFoundItemsQueryParams = zod.object({
  "status": zod.enum(['STORED', 'RESERVED', 'RETURNED', 'DISPOSED']).optional(),
  "venueId": zod.uuid().optional()
})
