/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';

export const getFoundItemByIdParams = zod.object({
  "id": zod.uuid()
})


export const updateFoundItemParams = zod.object({
  "id": zod.uuid()
})

export const updateFoundItemBody = zod.object({
  "photoKey": zod.string().optional(),
  "description": zod.string().optional(),
  "foundAt": zod.iso.datetime({}),
  "locationHint": zod.string().optional(),
  "status": zod.enum(['STORED', 'RESERVED', 'RETURNED', 'DISPOSED']),
  "venueId": zod.uuid(),
  "reporterId": zod.uuid(),
  "attributes": zod.object({
  "category": zod.string().optional(),
  "brand": zod.string().optional(),
  "color": zod.string().optional(),
  "marks": zod.array(zod.string()).optional()
}).optional()
})


export const createFoundItemBody = zod.object({
  "photoKey": zod.string().optional(),
  "description": zod.string().optional(),
  "foundAt": zod.iso.datetime({}),
  "locationHint": zod.string().optional(),
  "venueId": zod.uuid(),
  "reporterId": zod.uuid(),
  "attributes": zod.object({
  "category": zod.string().optional(),
  "brand": zod.string().optional(),
  "color": zod.string().optional(),
  "marks": zod.array(zod.string()).optional()
}).optional()
})
