/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CreatePickupScheduleRequestRecurrenceType = typeof CreatePickupScheduleRequestRecurrenceType[keyof typeof CreatePickupScheduleRequestRecurrenceType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePickupScheduleRequestRecurrenceType = {
  ONCE: 'ONCE',
  WEEKLY: 'WEEKLY',
} as const;
