/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CreatePickupScheduleRequestDayOfWeek = typeof CreatePickupScheduleRequestDayOfWeek[keyof typeof CreatePickupScheduleRequestDayOfWeek];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePickupScheduleRequestDayOfWeek = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const;
