/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PickupScheduleResponseRecurrenceType } from './pickupScheduleResponseRecurrenceType';
import type { PickupScheduleResponseDayOfWeek } from './pickupScheduleResponseDayOfWeek';

export interface PickupScheduleResponse {
  id?: string;
  recurrenceType?: PickupScheduleResponseRecurrenceType;
  startDate?: string;
  endDate?: string;
  dayOfWeek?: PickupScheduleResponseDayOfWeek;
  startTime?: string;
  endTime?: string;
  slotLengthInMinutes?: number;
  venueId?: string;
}
