/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PublicPickupResponse {
  id?: string;
  pickupAt?: string;
  venueId?: string;
  matchId?: string;
  email?: string;
  manageUrl?: string;
}
