/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UpdatePickupScheduleRequestRecurrenceType } from './updatePickupScheduleRequestRecurrenceType';
import type { UpdatePickupScheduleRequestDayOfWeek } from './updatePickupScheduleRequestDayOfWeek';

export interface UpdatePickupScheduleRequest {
  recurrenceType?: UpdatePickupScheduleRequestRecurrenceType;
  startDate: string;
  endDate?: string;
  dayOfWeek?: UpdatePickupScheduleRequestDayOfWeek;
  startTime: string;
  endTime: string;
  /** @minimum 1 */
  slotLengthInMinutes?: number;
  venueId?: string;
}
