/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateNotificationRequest,
  GetAllNotificationsParams,
  MatchContactStatusResponse,
  NotificationBlueprintResponse,
  NotificationResponse,
  UpdateNotificationRequest
} from '.././model';

import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType } from '../../mutator/custom-instance';




export const getNotificationById = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<NotificationResponse>(
      {url: `/api/notifications/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetNotificationByIdQueryKey = (id?: string,) => {
    return [
    `/api/notifications/${id}`
    ] as const;
    }

    
export const getGetNotificationByIdQueryOptions = <TData = Awaited<ReturnType<typeof getNotificationById>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotificationById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNotificationByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNotificationById>>> = ({ signal }) => getNotificationById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNotificationById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetNotificationByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getNotificationById>>>
export type GetNotificationByIdQueryError = ErrorType<unknown>


export function useGetNotificationById<TData = Awaited<ReturnType<typeof getNotificationById>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotificationById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotificationById>>,
          TError,
          Awaited<ReturnType<typeof getNotificationById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetNotificationById<TData = Awaited<ReturnType<typeof getNotificationById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotificationById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotificationById>>,
          TError,
          Awaited<ReturnType<typeof getNotificationById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetNotificationById<TData = Awaited<ReturnType<typeof getNotificationById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotificationById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetNotificationById<TData = Awaited<ReturnType<typeof getNotificationById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotificationById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetNotificationByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateNotification = (
    id: string,
    updateNotificationRequest: UpdateNotificationRequest,
 ) => {
      
      
      return customInstance<NotificationResponse>(
      {url: `/api/notifications/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateNotificationRequest
    },
      );
    }
  


export const getUpdateNotificationMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateNotification>>, TError,{id: string;data: UpdateNotificationRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateNotification>>, TError,{id: string;data: UpdateNotificationRequest}, TContext> => {

const mutationKey = ['updateNotification'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateNotification>>, {id: string;data: UpdateNotificationRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateNotification(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateNotificationMutationResult = NonNullable<Awaited<ReturnType<typeof updateNotification>>>
    export type UpdateNotificationMutationBody = UpdateNotificationRequest
    export type UpdateNotificationMutationError = ErrorType<unknown>

    export const useUpdateNotification = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateNotification>>, TError,{id: string;data: UpdateNotificationRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateNotification>>,
        TError,
        {id: string;data: UpdateNotificationRequest},
        TContext
      > => {

      const mutationOptions = getUpdateNotificationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getNotificationBlueprintById = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<NotificationBlueprintResponse>(
      {url: `/api/notifications/bluePrints/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetNotificationBlueprintByIdQueryKey = (id?: string,) => {
    return [
    `/api/notifications/bluePrints/${id}`
    ] as const;
    }

    
export const getGetNotificationBlueprintByIdQueryOptions = <TData = Awaited<ReturnType<typeof getNotificationBlueprintById>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotificationBlueprintById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNotificationBlueprintByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNotificationBlueprintById>>> = ({ signal }) => getNotificationBlueprintById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNotificationBlueprintById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetNotificationBlueprintByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getNotificationBlueprintById>>>
export type GetNotificationBlueprintByIdQueryError = ErrorType<unknown>


export function useGetNotificationBlueprintById<TData = Awaited<ReturnType<typeof getNotificationBlueprintById>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotificationBlueprintById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotificationBlueprintById>>,
          TError,
          Awaited<ReturnType<typeof getNotificationBlueprintById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetNotificationBlueprintById<TData = Awaited<ReturnType<typeof getNotificationBlueprintById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotificationBlueprintById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotificationBlueprintById>>,
          TError,
          Awaited<ReturnType<typeof getNotificationBlueprintById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetNotificationBlueprintById<TData = Awaited<ReturnType<typeof getNotificationBlueprintById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotificationBlueprintById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetNotificationBlueprintById<TData = Awaited<ReturnType<typeof getNotificationBlueprintById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotificationBlueprintById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetNotificationBlueprintByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateNotificationBlueprint = (
    id: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/notifications/bluePrints/${id}`, method: 'PUT'
    },
      );
    }
  


export const getUpdateNotificationBlueprintMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateNotificationBlueprint>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateNotificationBlueprint>>, TError,{id: string}, TContext> => {

const mutationKey = ['updateNotificationBlueprint'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateNotificationBlueprint>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  updateNotificationBlueprint(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateNotificationBlueprintMutationResult = NonNullable<Awaited<ReturnType<typeof updateNotificationBlueprint>>>
    
    export type UpdateNotificationBlueprintMutationError = ErrorType<unknown>

    export const useUpdateNotificationBlueprint = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateNotificationBlueprint>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateNotificationBlueprint>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getUpdateNotificationBlueprintMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAllNotifications = (
    params?: GetAllNotificationsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<NotificationResponse[]>(
      {url: `/api/notifications`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetAllNotificationsQueryKey = (params?: GetAllNotificationsParams,) => {
    return [
    `/api/notifications`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllNotificationsQueryOptions = <TData = Awaited<ReturnType<typeof getAllNotifications>>, TError = ErrorType<unknown>>(params?: GetAllNotificationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllNotifications>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllNotificationsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllNotifications>>> = ({ signal }) => getAllNotifications(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllNotifications>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAllNotificationsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllNotifications>>>
export type GetAllNotificationsQueryError = ErrorType<unknown>


export function useGetAllNotifications<TData = Awaited<ReturnType<typeof getAllNotifications>>, TError = ErrorType<unknown>>(
 params: undefined |  GetAllNotificationsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllNotifications>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllNotifications>>,
          TError,
          Awaited<ReturnType<typeof getAllNotifications>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllNotifications<TData = Awaited<ReturnType<typeof getAllNotifications>>, TError = ErrorType<unknown>>(
 params?: GetAllNotificationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllNotifications>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllNotifications>>,
          TError,
          Awaited<ReturnType<typeof getAllNotifications>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllNotifications<TData = Awaited<ReturnType<typeof getAllNotifications>>, TError = ErrorType<unknown>>(
 params?: GetAllNotificationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllNotifications>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAllNotifications<TData = Awaited<ReturnType<typeof getAllNotifications>>, TError = ErrorType<unknown>>(
 params?: GetAllNotificationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllNotifications>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAllNotificationsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const createNotification = (
    createNotificationRequest: CreateNotificationRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<NotificationResponse>(
      {url: `/api/notifications`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createNotificationRequest, signal
    },
      );
    }
  


export const getCreateNotificationMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createNotification>>, TError,{data: CreateNotificationRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createNotification>>, TError,{data: CreateNotificationRequest}, TContext> => {

const mutationKey = ['createNotification'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createNotification>>, {data: CreateNotificationRequest}> = (props) => {
          const {data} = props ?? {};

          return  createNotification(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateNotificationMutationResult = NonNullable<Awaited<ReturnType<typeof createNotification>>>
    export type CreateNotificationMutationBody = CreateNotificationRequest
    export type CreateNotificationMutationError = ErrorType<unknown>

    export const useCreateNotification = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createNotification>>, TError,{data: CreateNotificationRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createNotification>>,
        TError,
        {data: CreateNotificationRequest},
        TContext
      > => {

      const mutationOptions = getCreateNotificationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getNotificationBlueprints = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<NotificationBlueprintResponse[]>(
      {url: `/api/notifications/bluePrints`, method: 'GET', signal
    },
      );
    }
  



export const getGetNotificationBlueprintsQueryKey = () => {
    return [
    `/api/notifications/bluePrints`
    ] as const;
    }

    
export const getGetNotificationBlueprintsQueryOptions = <TData = Awaited<ReturnType<typeof getNotificationBlueprints>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotificationBlueprints>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNotificationBlueprintsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNotificationBlueprints>>> = ({ signal }) => getNotificationBlueprints(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNotificationBlueprints>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetNotificationBlueprintsQueryResult = NonNullable<Awaited<ReturnType<typeof getNotificationBlueprints>>>
export type GetNotificationBlueprintsQueryError = ErrorType<unknown>


export function useGetNotificationBlueprints<TData = Awaited<ReturnType<typeof getNotificationBlueprints>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotificationBlueprints>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotificationBlueprints>>,
          TError,
          Awaited<ReturnType<typeof getNotificationBlueprints>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetNotificationBlueprints<TData = Awaited<ReturnType<typeof getNotificationBlueprints>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotificationBlueprints>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotificationBlueprints>>,
          TError,
          Awaited<ReturnType<typeof getNotificationBlueprints>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetNotificationBlueprints<TData = Awaited<ReturnType<typeof getNotificationBlueprints>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotificationBlueprints>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetNotificationBlueprints<TData = Awaited<ReturnType<typeof getNotificationBlueprints>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotificationBlueprints>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetNotificationBlueprintsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const createNotificationBlueprint = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/notifications/bluePrints`, method: 'POST', signal
    },
      );
    }
  


export const getCreateNotificationBlueprintMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createNotificationBlueprint>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createNotificationBlueprint>>, TError,void, TContext> => {

const mutationKey = ['createNotificationBlueprint'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createNotificationBlueprint>>, void> = () => {
          

          return  createNotificationBlueprint()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateNotificationBlueprintMutationResult = NonNullable<Awaited<ReturnType<typeof createNotificationBlueprint>>>
    
    export type CreateNotificationBlueprintMutationError = ErrorType<unknown>

    export const useCreateNotificationBlueprint = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createNotificationBlueprint>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createNotificationBlueprint>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getCreateNotificationBlueprintMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getMatchContacts = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<MatchContactStatusResponse[]>(
      {url: `/api/notifications/match-contacts`, method: 'GET', signal
    },
      );
    }
  



export const getGetMatchContactsQueryKey = () => {
    return [
    `/api/notifications/match-contacts`
    ] as const;
    }

    
export const getGetMatchContactsQueryOptions = <TData = Awaited<ReturnType<typeof getMatchContacts>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatchContacts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMatchContactsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMatchContacts>>> = ({ signal }) => getMatchContacts(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMatchContacts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetMatchContactsQueryResult = NonNullable<Awaited<ReturnType<typeof getMatchContacts>>>
export type GetMatchContactsQueryError = ErrorType<unknown>


export function useGetMatchContacts<TData = Awaited<ReturnType<typeof getMatchContacts>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatchContacts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMatchContacts>>,
          TError,
          Awaited<ReturnType<typeof getMatchContacts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetMatchContacts<TData = Awaited<ReturnType<typeof getMatchContacts>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatchContacts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMatchContacts>>,
          TError,
          Awaited<ReturnType<typeof getMatchContacts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetMatchContacts<TData = Awaited<ReturnType<typeof getMatchContacts>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatchContacts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetMatchContacts<TData = Awaited<ReturnType<typeof getMatchContacts>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatchContacts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetMatchContactsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




