/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CreateUserRequestRole } from './createUserRequestRole';

export interface CreateUserRequest {
  /** @minLength 1 */
  email: string;
  role: CreateUserRequestRole;
  /**
   * @minLength 8
   * @maxLength 2147483647
   */
  password: string;
}
