/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UpdateUserRequestRole } from './updateUserRequestRole';

export interface UpdateUserRequest {
  /** @minLength 1 */
  email: string;
  role: UpdateUserRequestRole;
}
