/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserResponseRole } from './userResponseRole';

export interface UserResponse {
  id?: string;
  email?: string;
  role?: UserResponseRole;
}
