/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface VenueKpiResponse {
  venueId?: string;
  totalFoundItems?: number;
  totalLostItems?: number;
  totalMatches?: number;
  pendingMatches?: number;
}
