/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CountLostReportsStatus } from './countLostReportsStatus';

export type CountLostReportsParams = {
status?: CountLostReportsStatus;
venueId?: string;
};
