/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CreateLostReportRequest } from './createLostReportRequest';

export type CreateLostReportWithPhotoBodyOne = {
  request: CreateLostReportRequest;
  photo?: Blob;
};
