/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ItemAttributesDto } from './itemAttributesDto';

export interface CreateLostReportRequest {
  photoKey?: string;
  /** @minLength 1 */
  description: string;
  lostAt: string;
  location?: string;
  /** @minLength 1 */
  contactEmail: string;
  attributes?: ItemAttributesDto;
}
