/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { GetLostReportHistogram1Status } from './getLostReportHistogram1Status';

export type GetLostReportHistogram1Params = {
status?: GetLostReportHistogram1Status;
venueId?: string;
};
