/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UpdateLostReportRequestStatus } from './updateLostReportRequestStatus';
import type { ItemAttributesDto } from './itemAttributesDto';

export interface UpdateLostReportRequest {
  /** @minLength 1 */
  description: string;
  lostAt: string;
  location?: string;
  status: UpdateLostReportRequestStatus;
  venueId?: string;
  /** @minLength 1 */
  contactEmail: string;
  attributes?: ItemAttributesDto;
}
