/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CountLostReports1Params,
  CountLostReportsParams,
  CountResponse,
  CreateLostReportWithPhoto1Body,
  CreateLostReportWithPhotoBody,
  GetAllLostReports1Params,
  GetAllLostReportsParams,
  GetLostReportHistogram1Params,
  GetLostReportHistogramParams,
  HistogramResponse,
  LostReportResponse,
  PhotoUrlResponse,
  UpdateLostReportPhoto1Body,
  UpdateLostReportPhotoBody,
  UpdateLostReportRequest
} from '.././model';

import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType } from '../../mutator/custom-instance';




export const getLostReportPhoto = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Blob>(
      {url: `/api/lost-items/${id}/photo`, method: 'GET',
        responseType: 'blob', signal
    },
      );
    }
  



export const getGetLostReportPhotoQueryKey = (id?: string,) => {
    return [
    `/api/lost-items/${id}/photo`
    ] as const;
    }

    
export const getGetLostReportPhotoQueryOptions = <TData = Awaited<ReturnType<typeof getLostReportPhoto>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhoto>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLostReportPhotoQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLostReportPhoto>>> = ({ signal }) => getLostReportPhoto(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhoto>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetLostReportPhotoQueryResult = NonNullable<Awaited<ReturnType<typeof getLostReportPhoto>>>
export type GetLostReportPhotoQueryError = ErrorType<unknown>


export function useGetLostReportPhoto<TData = Awaited<ReturnType<typeof getLostReportPhoto>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhoto>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportPhoto>>,
          TError,
          Awaited<ReturnType<typeof getLostReportPhoto>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportPhoto<TData = Awaited<ReturnType<typeof getLostReportPhoto>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhoto>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportPhoto>>,
          TError,
          Awaited<ReturnType<typeof getLostReportPhoto>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportPhoto<TData = Awaited<ReturnType<typeof getLostReportPhoto>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhoto>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetLostReportPhoto<TData = Awaited<ReturnType<typeof getLostReportPhoto>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhoto>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetLostReportPhotoQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateLostReportPhoto = (
    id: string,
    updateLostReportPhotoBody: UpdateLostReportPhotoBody,
 ) => {
      
      const formData = new FormData();
formData.append(`photo`, updateLostReportPhotoBody.photo)

      return customInstance<LostReportResponse>(
      {url: `/api/lost-items/${id}/photo`, method: 'PUT',
       data: formData
    },
      );
    }
  


export const getUpdateLostReportPhotoMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLostReportPhoto>>, TError,{id: string;data: UpdateLostReportPhotoBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateLostReportPhoto>>, TError,{id: string;data: UpdateLostReportPhotoBody}, TContext> => {

const mutationKey = ['updateLostReportPhoto'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateLostReportPhoto>>, {id: string;data: UpdateLostReportPhotoBody}> = (props) => {
          const {id,data} = props ?? {};

          return  updateLostReportPhoto(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateLostReportPhotoMutationResult = NonNullable<Awaited<ReturnType<typeof updateLostReportPhoto>>>
    export type UpdateLostReportPhotoMutationBody = UpdateLostReportPhotoBody
    export type UpdateLostReportPhotoMutationError = ErrorType<unknown>

    export const useUpdateLostReportPhoto = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLostReportPhoto>>, TError,{id: string;data: UpdateLostReportPhotoBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateLostReportPhoto>>,
        TError,
        {id: string;data: UpdateLostReportPhotoBody},
        TContext
      > => {

      const mutationOptions = getUpdateLostReportPhotoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getLostReportPhoto1 = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Blob>(
      {url: `/api/lost-reports/${id}/photo`, method: 'GET',
        responseType: 'blob', signal
    },
      );
    }
  



export const getGetLostReportPhoto1QueryKey = (id?: string,) => {
    return [
    `/api/lost-reports/${id}/photo`
    ] as const;
    }

    
export const getGetLostReportPhoto1QueryOptions = <TData = Awaited<ReturnType<typeof getLostReportPhoto1>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhoto1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLostReportPhoto1QueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLostReportPhoto1>>> = ({ signal }) => getLostReportPhoto1(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhoto1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetLostReportPhoto1QueryResult = NonNullable<Awaited<ReturnType<typeof getLostReportPhoto1>>>
export type GetLostReportPhoto1QueryError = ErrorType<unknown>


export function useGetLostReportPhoto1<TData = Awaited<ReturnType<typeof getLostReportPhoto1>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhoto1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportPhoto1>>,
          TError,
          Awaited<ReturnType<typeof getLostReportPhoto1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportPhoto1<TData = Awaited<ReturnType<typeof getLostReportPhoto1>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhoto1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportPhoto1>>,
          TError,
          Awaited<ReturnType<typeof getLostReportPhoto1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportPhoto1<TData = Awaited<ReturnType<typeof getLostReportPhoto1>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhoto1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetLostReportPhoto1<TData = Awaited<ReturnType<typeof getLostReportPhoto1>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhoto1>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetLostReportPhoto1QueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateLostReportPhoto1 = (
    id: string,
    updateLostReportPhoto1Body: UpdateLostReportPhoto1Body,
 ) => {
      
      const formData = new FormData();
formData.append(`photo`, updateLostReportPhoto1Body.photo)

      return customInstance<LostReportResponse>(
      {url: `/api/lost-reports/${id}/photo`, method: 'PUT',
       data: formData
    },
      );
    }
  


export const getUpdateLostReportPhoto1MutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLostReportPhoto1>>, TError,{id: string;data: UpdateLostReportPhoto1Body}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateLostReportPhoto1>>, TError,{id: string;data: UpdateLostReportPhoto1Body}, TContext> => {

const mutationKey = ['updateLostReportPhoto1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateLostReportPhoto1>>, {id: string;data: UpdateLostReportPhoto1Body}> = (props) => {
          const {id,data} = props ?? {};

          return  updateLostReportPhoto1(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateLostReportPhoto1MutationResult = NonNullable<Awaited<ReturnType<typeof updateLostReportPhoto1>>>
    export type UpdateLostReportPhoto1MutationBody = UpdateLostReportPhoto1Body
    export type UpdateLostReportPhoto1MutationError = ErrorType<unknown>

    export const useUpdateLostReportPhoto1 = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLostReportPhoto1>>, TError,{id: string;data: UpdateLostReportPhoto1Body}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateLostReportPhoto1>>,
        TError,
        {id: string;data: UpdateLostReportPhoto1Body},
        TContext
      > => {

      const mutationOptions = getUpdateLostReportPhoto1MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getLostReportById = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<LostReportResponse>(
      {url: `/api/lost-reports/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetLostReportByIdQueryKey = (id?: string,) => {
    return [
    `/api/lost-reports/${id}`
    ] as const;
    }

    
export const getGetLostReportByIdQueryOptions = <TData = Awaited<ReturnType<typeof getLostReportById>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLostReportByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLostReportById>>> = ({ signal }) => getLostReportById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLostReportById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetLostReportByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getLostReportById>>>
export type GetLostReportByIdQueryError = ErrorType<unknown>


export function useGetLostReportById<TData = Awaited<ReturnType<typeof getLostReportById>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportById>>,
          TError,
          Awaited<ReturnType<typeof getLostReportById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportById<TData = Awaited<ReturnType<typeof getLostReportById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportById>>,
          TError,
          Awaited<ReturnType<typeof getLostReportById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportById<TData = Awaited<ReturnType<typeof getLostReportById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetLostReportById<TData = Awaited<ReturnType<typeof getLostReportById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetLostReportByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateLostReport = (
    id: string,
    updateLostReportRequest: UpdateLostReportRequest,
 ) => {
      
      
      return customInstance<LostReportResponse>(
      {url: `/api/lost-reports/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateLostReportRequest
    },
      );
    }
  


export const getUpdateLostReportMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLostReport>>, TError,{id: string;data: UpdateLostReportRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateLostReport>>, TError,{id: string;data: UpdateLostReportRequest}, TContext> => {

const mutationKey = ['updateLostReport'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateLostReport>>, {id: string;data: UpdateLostReportRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateLostReport(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateLostReportMutationResult = NonNullable<Awaited<ReturnType<typeof updateLostReport>>>
    export type UpdateLostReportMutationBody = UpdateLostReportRequest
    export type UpdateLostReportMutationError = ErrorType<unknown>

    export const useUpdateLostReport = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLostReport>>, TError,{id: string;data: UpdateLostReportRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateLostReport>>,
        TError,
        {id: string;data: UpdateLostReportRequest},
        TContext
      > => {

      const mutationOptions = getUpdateLostReportMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getLostReportById1 = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<LostReportResponse>(
      {url: `/api/lost-items/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetLostReportById1QueryKey = (id?: string,) => {
    return [
    `/api/lost-items/${id}`
    ] as const;
    }

    
export const getGetLostReportById1QueryOptions = <TData = Awaited<ReturnType<typeof getLostReportById1>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLostReportById1QueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLostReportById1>>> = ({ signal }) => getLostReportById1(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLostReportById1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetLostReportById1QueryResult = NonNullable<Awaited<ReturnType<typeof getLostReportById1>>>
export type GetLostReportById1QueryError = ErrorType<unknown>


export function useGetLostReportById1<TData = Awaited<ReturnType<typeof getLostReportById1>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportById1>>,
          TError,
          Awaited<ReturnType<typeof getLostReportById1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportById1<TData = Awaited<ReturnType<typeof getLostReportById1>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportById1>>,
          TError,
          Awaited<ReturnType<typeof getLostReportById1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportById1<TData = Awaited<ReturnType<typeof getLostReportById1>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetLostReportById1<TData = Awaited<ReturnType<typeof getLostReportById1>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById1>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetLostReportById1QueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateLostReport1 = (
    id: string,
    updateLostReportRequest: UpdateLostReportRequest,
 ) => {
      
      
      return customInstance<LostReportResponse>(
      {url: `/api/lost-items/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateLostReportRequest
    },
      );
    }
  


export const getUpdateLostReport1MutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLostReport1>>, TError,{id: string;data: UpdateLostReportRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateLostReport1>>, TError,{id: string;data: UpdateLostReportRequest}, TContext> => {

const mutationKey = ['updateLostReport1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateLostReport1>>, {id: string;data: UpdateLostReportRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateLostReport1(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateLostReport1MutationResult = NonNullable<Awaited<ReturnType<typeof updateLostReport1>>>
    export type UpdateLostReport1MutationBody = UpdateLostReportRequest
    export type UpdateLostReport1MutationError = ErrorType<unknown>

    export const useUpdateLostReport1 = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLostReport1>>, TError,{id: string;data: UpdateLostReportRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateLostReport1>>,
        TError,
        {id: string;data: UpdateLostReportRequest},
        TContext
      > => {

      const mutationOptions = getUpdateLostReport1MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAllLostReports = (
    params?: GetAllLostReportsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<LostReportResponse[]>(
      {url: `/api/lost-items`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetAllLostReportsQueryKey = (params?: GetAllLostReportsParams,) => {
    return [
    `/api/lost-items`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllLostReportsQueryOptions = <TData = Awaited<ReturnType<typeof getAllLostReports>>, TError = ErrorType<unknown>>(params?: GetAllLostReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllLostReportsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllLostReports>>> = ({ signal }) => getAllLostReports(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAllLostReportsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllLostReports>>>
export type GetAllLostReportsQueryError = ErrorType<unknown>


export function useGetAllLostReports<TData = Awaited<ReturnType<typeof getAllLostReports>>, TError = ErrorType<unknown>>(
 params: undefined |  GetAllLostReportsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllLostReports>>,
          TError,
          Awaited<ReturnType<typeof getAllLostReports>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllLostReports<TData = Awaited<ReturnType<typeof getAllLostReports>>, TError = ErrorType<unknown>>(
 params?: GetAllLostReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllLostReports>>,
          TError,
          Awaited<ReturnType<typeof getAllLostReports>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllLostReports<TData = Awaited<ReturnType<typeof getAllLostReports>>, TError = ErrorType<unknown>>(
 params?: GetAllLostReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAllLostReports<TData = Awaited<ReturnType<typeof getAllLostReports>>, TError = ErrorType<unknown>>(
 params?: GetAllLostReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAllLostReportsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const createLostReportWithPhoto = (
    createLostReportWithPhotoBody: CreateLostReportWithPhotoBody,
 signal?: AbortSignal
) => {
      
      const formData = new FormData();
formData.append(`request`, new Blob([JSON.stringify(createLostReportWithPhotoBody.request)], { type: 'application/json' }));
if(createLostReportWithPhotoBody.photo !== undefined) {
 formData.append(`photo`, createLostReportWithPhotoBody.photo)
 }

      return customInstance<LostReportResponse>(
      {url: `/api/lost-items`, method: 'POST',
       data: formData, signal
    },
      );
    }
  


export const getCreateLostReportWithPhotoMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLostReportWithPhoto>>, TError,{data: CreateLostReportWithPhotoBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createLostReportWithPhoto>>, TError,{data: CreateLostReportWithPhotoBody}, TContext> => {

const mutationKey = ['createLostReportWithPhoto'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createLostReportWithPhoto>>, {data: CreateLostReportWithPhotoBody}> = (props) => {
          const {data} = props ?? {};

          return  createLostReportWithPhoto(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateLostReportWithPhotoMutationResult = NonNullable<Awaited<ReturnType<typeof createLostReportWithPhoto>>>
    export type CreateLostReportWithPhotoMutationBody = CreateLostReportWithPhotoBody
    export type CreateLostReportWithPhotoMutationError = ErrorType<unknown>

    export const useCreateLostReportWithPhoto = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLostReportWithPhoto>>, TError,{data: CreateLostReportWithPhotoBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createLostReportWithPhoto>>,
        TError,
        {data: CreateLostReportWithPhotoBody},
        TContext
      > => {

      const mutationOptions = getCreateLostReportWithPhotoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAllLostReports1 = (
    params?: GetAllLostReports1Params,
 signal?: AbortSignal
) => {
      
      
      return customInstance<LostReportResponse[]>(
      {url: `/api/lost-reports`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetAllLostReports1QueryKey = (params?: GetAllLostReports1Params,) => {
    return [
    `/api/lost-reports`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllLostReports1QueryOptions = <TData = Awaited<ReturnType<typeof getAllLostReports1>>, TError = ErrorType<unknown>>(params?: GetAllLostReports1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllLostReports1QueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllLostReports1>>> = ({ signal }) => getAllLostReports1(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAllLostReports1QueryResult = NonNullable<Awaited<ReturnType<typeof getAllLostReports1>>>
export type GetAllLostReports1QueryError = ErrorType<unknown>


export function useGetAllLostReports1<TData = Awaited<ReturnType<typeof getAllLostReports1>>, TError = ErrorType<unknown>>(
 params: undefined |  GetAllLostReports1Params, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllLostReports1>>,
          TError,
          Awaited<ReturnType<typeof getAllLostReports1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllLostReports1<TData = Awaited<ReturnType<typeof getAllLostReports1>>, TError = ErrorType<unknown>>(
 params?: GetAllLostReports1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllLostReports1>>,
          TError,
          Awaited<ReturnType<typeof getAllLostReports1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllLostReports1<TData = Awaited<ReturnType<typeof getAllLostReports1>>, TError = ErrorType<unknown>>(
 params?: GetAllLostReports1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAllLostReports1<TData = Awaited<ReturnType<typeof getAllLostReports1>>, TError = ErrorType<unknown>>(
 params?: GetAllLostReports1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports1>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAllLostReports1QueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const createLostReportWithPhoto1 = (
    createLostReportWithPhoto1Body: CreateLostReportWithPhoto1Body,
 signal?: AbortSignal
) => {
      
      const formData = new FormData();
formData.append(`request`, new Blob([JSON.stringify(createLostReportWithPhoto1Body.request)], { type: 'application/json' }));
if(createLostReportWithPhoto1Body.photo !== undefined) {
 formData.append(`photo`, createLostReportWithPhoto1Body.photo)
 }

      return customInstance<LostReportResponse>(
      {url: `/api/lost-reports`, method: 'POST',
       data: formData, signal
    },
      );
    }
  


export const getCreateLostReportWithPhoto1MutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLostReportWithPhoto1>>, TError,{data: CreateLostReportWithPhoto1Body}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createLostReportWithPhoto1>>, TError,{data: CreateLostReportWithPhoto1Body}, TContext> => {

const mutationKey = ['createLostReportWithPhoto1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createLostReportWithPhoto1>>, {data: CreateLostReportWithPhoto1Body}> = (props) => {
          const {data} = props ?? {};

          return  createLostReportWithPhoto1(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateLostReportWithPhoto1MutationResult = NonNullable<Awaited<ReturnType<typeof createLostReportWithPhoto1>>>
    export type CreateLostReportWithPhoto1MutationBody = CreateLostReportWithPhoto1Body
    export type CreateLostReportWithPhoto1MutationError = ErrorType<unknown>

    export const useCreateLostReportWithPhoto1 = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLostReportWithPhoto1>>, TError,{data: CreateLostReportWithPhoto1Body}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createLostReportWithPhoto1>>,
        TError,
        {data: CreateLostReportWithPhoto1Body},
        TContext
      > => {

      const mutationOptions = getCreateLostReportWithPhoto1MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getLostReportPhotoUrl = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PhotoUrlResponse>(
      {url: `/api/lost-items/${id}/photo-url`, method: 'GET', signal
    },
      );
    }
  



export const getGetLostReportPhotoUrlQueryKey = (id?: string,) => {
    return [
    `/api/lost-items/${id}/photo-url`
    ] as const;
    }

    
export const getGetLostReportPhotoUrlQueryOptions = <TData = Awaited<ReturnType<typeof getLostReportPhotoUrl>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhotoUrl>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLostReportPhotoUrlQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLostReportPhotoUrl>>> = ({ signal }) => getLostReportPhotoUrl(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhotoUrl>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetLostReportPhotoUrlQueryResult = NonNullable<Awaited<ReturnType<typeof getLostReportPhotoUrl>>>
export type GetLostReportPhotoUrlQueryError = ErrorType<unknown>


export function useGetLostReportPhotoUrl<TData = Awaited<ReturnType<typeof getLostReportPhotoUrl>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhotoUrl>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportPhotoUrl>>,
          TError,
          Awaited<ReturnType<typeof getLostReportPhotoUrl>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportPhotoUrl<TData = Awaited<ReturnType<typeof getLostReportPhotoUrl>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhotoUrl>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportPhotoUrl>>,
          TError,
          Awaited<ReturnType<typeof getLostReportPhotoUrl>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportPhotoUrl<TData = Awaited<ReturnType<typeof getLostReportPhotoUrl>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhotoUrl>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetLostReportPhotoUrl<TData = Awaited<ReturnType<typeof getLostReportPhotoUrl>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhotoUrl>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetLostReportPhotoUrlQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getLostReportPhotoUrl1 = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PhotoUrlResponse>(
      {url: `/api/lost-reports/${id}/photo-url`, method: 'GET', signal
    },
      );
    }
  



export const getGetLostReportPhotoUrl1QueryKey = (id?: string,) => {
    return [
    `/api/lost-reports/${id}/photo-url`
    ] as const;
    }

    
export const getGetLostReportPhotoUrl1QueryOptions = <TData = Awaited<ReturnType<typeof getLostReportPhotoUrl1>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhotoUrl1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLostReportPhotoUrl1QueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLostReportPhotoUrl1>>> = ({ signal }) => getLostReportPhotoUrl1(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhotoUrl1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetLostReportPhotoUrl1QueryResult = NonNullable<Awaited<ReturnType<typeof getLostReportPhotoUrl1>>>
export type GetLostReportPhotoUrl1QueryError = ErrorType<unknown>


export function useGetLostReportPhotoUrl1<TData = Awaited<ReturnType<typeof getLostReportPhotoUrl1>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhotoUrl1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportPhotoUrl1>>,
          TError,
          Awaited<ReturnType<typeof getLostReportPhotoUrl1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportPhotoUrl1<TData = Awaited<ReturnType<typeof getLostReportPhotoUrl1>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhotoUrl1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportPhotoUrl1>>,
          TError,
          Awaited<ReturnType<typeof getLostReportPhotoUrl1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportPhotoUrl1<TData = Awaited<ReturnType<typeof getLostReportPhotoUrl1>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhotoUrl1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetLostReportPhotoUrl1<TData = Awaited<ReturnType<typeof getLostReportPhotoUrl1>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhotoUrl1>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetLostReportPhotoUrl1QueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getLostReportHistogram = (
    params?: GetLostReportHistogramParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<HistogramResponse>(
      {url: `/api/lost-items/histogram`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetLostReportHistogramQueryKey = (params?: GetLostReportHistogramParams,) => {
    return [
    `/api/lost-items/histogram`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetLostReportHistogramQueryOptions = <TData = Awaited<ReturnType<typeof getLostReportHistogram>>, TError = ErrorType<unknown>>(params?: GetLostReportHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLostReportHistogramQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLostReportHistogram>>> = ({ signal }) => getLostReportHistogram(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetLostReportHistogramQueryResult = NonNullable<Awaited<ReturnType<typeof getLostReportHistogram>>>
export type GetLostReportHistogramQueryError = ErrorType<unknown>


export function useGetLostReportHistogram<TData = Awaited<ReturnType<typeof getLostReportHistogram>>, TError = ErrorType<unknown>>(
 params: undefined |  GetLostReportHistogramParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportHistogram>>,
          TError,
          Awaited<ReturnType<typeof getLostReportHistogram>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportHistogram<TData = Awaited<ReturnType<typeof getLostReportHistogram>>, TError = ErrorType<unknown>>(
 params?: GetLostReportHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportHistogram>>,
          TError,
          Awaited<ReturnType<typeof getLostReportHistogram>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportHistogram<TData = Awaited<ReturnType<typeof getLostReportHistogram>>, TError = ErrorType<unknown>>(
 params?: GetLostReportHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetLostReportHistogram<TData = Awaited<ReturnType<typeof getLostReportHistogram>>, TError = ErrorType<unknown>>(
 params?: GetLostReportHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetLostReportHistogramQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getLostReportHistogram1 = (
    params?: GetLostReportHistogram1Params,
 signal?: AbortSignal
) => {
      
      
      return customInstance<HistogramResponse>(
      {url: `/api/lost-reports/histogram`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetLostReportHistogram1QueryKey = (params?: GetLostReportHistogram1Params,) => {
    return [
    `/api/lost-reports/histogram`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetLostReportHistogram1QueryOptions = <TData = Awaited<ReturnType<typeof getLostReportHistogram1>>, TError = ErrorType<unknown>>(params?: GetLostReportHistogram1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLostReportHistogram1QueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLostReportHistogram1>>> = ({ signal }) => getLostReportHistogram1(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetLostReportHistogram1QueryResult = NonNullable<Awaited<ReturnType<typeof getLostReportHistogram1>>>
export type GetLostReportHistogram1QueryError = ErrorType<unknown>


export function useGetLostReportHistogram1<TData = Awaited<ReturnType<typeof getLostReportHistogram1>>, TError = ErrorType<unknown>>(
 params: undefined |  GetLostReportHistogram1Params, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportHistogram1>>,
          TError,
          Awaited<ReturnType<typeof getLostReportHistogram1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportHistogram1<TData = Awaited<ReturnType<typeof getLostReportHistogram1>>, TError = ErrorType<unknown>>(
 params?: GetLostReportHistogram1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportHistogram1>>,
          TError,
          Awaited<ReturnType<typeof getLostReportHistogram1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportHistogram1<TData = Awaited<ReturnType<typeof getLostReportHistogram1>>, TError = ErrorType<unknown>>(
 params?: GetLostReportHistogram1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetLostReportHistogram1<TData = Awaited<ReturnType<typeof getLostReportHistogram1>>, TError = ErrorType<unknown>>(
 params?: GetLostReportHistogram1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram1>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetLostReportHistogram1QueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const countLostReports = (
    params?: CountLostReportsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CountResponse>(
      {url: `/api/lost-items/count`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getCountLostReportsQueryKey = (params?: CountLostReportsParams,) => {
    return [
    `/api/lost-items/count`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getCountLostReportsQueryOptions = <TData = Awaited<ReturnType<typeof countLostReports>>, TError = ErrorType<unknown>>(params?: CountLostReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countLostReports>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCountLostReportsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof countLostReports>>> = ({ signal }) => countLostReports(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof countLostReports>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type CountLostReportsQueryResult = NonNullable<Awaited<ReturnType<typeof countLostReports>>>
export type CountLostReportsQueryError = ErrorType<unknown>


export function useCountLostReports<TData = Awaited<ReturnType<typeof countLostReports>>, TError = ErrorType<unknown>>(
 params: undefined |  CountLostReportsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof countLostReports>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof countLostReports>>,
          TError,
          Awaited<ReturnType<typeof countLostReports>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useCountLostReports<TData = Awaited<ReturnType<typeof countLostReports>>, TError = ErrorType<unknown>>(
 params?: CountLostReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countLostReports>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof countLostReports>>,
          TError,
          Awaited<ReturnType<typeof countLostReports>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useCountLostReports<TData = Awaited<ReturnType<typeof countLostReports>>, TError = ErrorType<unknown>>(
 params?: CountLostReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countLostReports>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useCountLostReports<TData = Awaited<ReturnType<typeof countLostReports>>, TError = ErrorType<unknown>>(
 params?: CountLostReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countLostReports>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getCountLostReportsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const countLostReports1 = (
    params?: CountLostReports1Params,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CountResponse>(
      {url: `/api/lost-reports/count`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getCountLostReports1QueryKey = (params?: CountLostReports1Params,) => {
    return [
    `/api/lost-reports/count`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getCountLostReports1QueryOptions = <TData = Awaited<ReturnType<typeof countLostReports1>>, TError = ErrorType<unknown>>(params?: CountLostReports1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countLostReports1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCountLostReports1QueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof countLostReports1>>> = ({ signal }) => countLostReports1(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof countLostReports1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type CountLostReports1QueryResult = NonNullable<Awaited<ReturnType<typeof countLostReports1>>>
export type CountLostReports1QueryError = ErrorType<unknown>


export function useCountLostReports1<TData = Awaited<ReturnType<typeof countLostReports1>>, TError = ErrorType<unknown>>(
 params: undefined |  CountLostReports1Params, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof countLostReports1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof countLostReports1>>,
          TError,
          Awaited<ReturnType<typeof countLostReports1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useCountLostReports1<TData = Awaited<ReturnType<typeof countLostReports1>>, TError = ErrorType<unknown>>(
 params?: CountLostReports1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countLostReports1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof countLostReports1>>,
          TError,
          Awaited<ReturnType<typeof countLostReports1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useCountLostReports1<TData = Awaited<ReturnType<typeof countLostReports1>>, TError = ErrorType<unknown>>(
 params?: CountLostReports1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countLostReports1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useCountLostReports1<TData = Awaited<ReturnType<typeof countLostReports1>>, TError = ErrorType<unknown>>(
 params?: CountLostReports1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countLostReports1>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getCountLostReports1QueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




