/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CountLostReportsParams,
  CountResponse,
  CreateLostReportRequest,
  GetAllLostReportsParams,
  GetLostReportHistogramParams,
  HistogramResponse,
  LostReportResponse,
  PhotoUrlResponse,
  UpdateLostReportPhotoBody,
  UpdateLostReportRequest
} from '.././model';

import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType } from '../../mutator/custom-instance';




export const getLostReportById = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<LostReportResponse>(
      {url: `/api/lost-items/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetLostReportByIdQueryKey = (id?: string,) => {
    return [
    `/api/lost-items/${id}`
    ] as const;
    }

    
export const getGetLostReportByIdQueryOptions = <TData = Awaited<ReturnType<typeof getLostReportById>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLostReportByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLostReportById>>> = ({ signal }) => getLostReportById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLostReportById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetLostReportByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getLostReportById>>>
export type GetLostReportByIdQueryError = ErrorType<unknown>


export function useGetLostReportById<TData = Awaited<ReturnType<typeof getLostReportById>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportById>>,
          TError,
          Awaited<ReturnType<typeof getLostReportById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportById<TData = Awaited<ReturnType<typeof getLostReportById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportById>>,
          TError,
          Awaited<ReturnType<typeof getLostReportById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportById<TData = Awaited<ReturnType<typeof getLostReportById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetLostReportById<TData = Awaited<ReturnType<typeof getLostReportById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetLostReportByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateLostReport = (
    id: string,
    updateLostReportRequest: UpdateLostReportRequest,
 ) => {
      
      
      return customInstance<LostReportResponse>(
      {url: `/api/lost-items/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateLostReportRequest
    },
      );
    }
  


export const getUpdateLostReportMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLostReport>>, TError,{id: string;data: UpdateLostReportRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateLostReport>>, TError,{id: string;data: UpdateLostReportRequest}, TContext> => {

const mutationKey = ['updateLostReport'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateLostReport>>, {id: string;data: UpdateLostReportRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateLostReport(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateLostReportMutationResult = NonNullable<Awaited<ReturnType<typeof updateLostReport>>>
    export type UpdateLostReportMutationBody = UpdateLostReportRequest
    export type UpdateLostReportMutationError = ErrorType<unknown>

    export const useUpdateLostReport = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLostReport>>, TError,{id: string;data: UpdateLostReportRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateLostReport>>,
        TError,
        {id: string;data: UpdateLostReportRequest},
        TContext
      > => {

      const mutationOptions = getUpdateLostReportMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getLostReportPhoto = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Blob>(
      {url: `/api/lost-items/${id}/photo`, method: 'GET',
        responseType: 'blob', signal
    },
      );
    }
  



export const getGetLostReportPhotoQueryKey = (id?: string,) => {
    return [
    `/api/lost-items/${id}/photo`
    ] as const;
    }

    
export const getGetLostReportPhotoQueryOptions = <TData = Awaited<ReturnType<typeof getLostReportPhoto>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhoto>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLostReportPhotoQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLostReportPhoto>>> = ({ signal }) => getLostReportPhoto(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhoto>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetLostReportPhotoQueryResult = NonNullable<Awaited<ReturnType<typeof getLostReportPhoto>>>
export type GetLostReportPhotoQueryError = ErrorType<unknown>


export function useGetLostReportPhoto<TData = Awaited<ReturnType<typeof getLostReportPhoto>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhoto>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportPhoto>>,
          TError,
          Awaited<ReturnType<typeof getLostReportPhoto>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportPhoto<TData = Awaited<ReturnType<typeof getLostReportPhoto>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhoto>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportPhoto>>,
          TError,
          Awaited<ReturnType<typeof getLostReportPhoto>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportPhoto<TData = Awaited<ReturnType<typeof getLostReportPhoto>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhoto>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetLostReportPhoto<TData = Awaited<ReturnType<typeof getLostReportPhoto>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhoto>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetLostReportPhotoQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateLostReportPhoto = (
    id: string,
    updateLostReportPhotoBody: UpdateLostReportPhotoBody,
 ) => {
      
      const formData = new FormData();
formData.append(`photo`, updateLostReportPhotoBody.photo)

      return customInstance<LostReportResponse>(
      {url: `/api/lost-items/${id}/photo`, method: 'PUT',
       data: formData
    },
      );
    }
  


export const getUpdateLostReportPhotoMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLostReportPhoto>>, TError,{id: string;data: UpdateLostReportPhotoBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateLostReportPhoto>>, TError,{id: string;data: UpdateLostReportPhotoBody}, TContext> => {

const mutationKey = ['updateLostReportPhoto'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateLostReportPhoto>>, {id: string;data: UpdateLostReportPhotoBody}> = (props) => {
          const {id,data} = props ?? {};

          return  updateLostReportPhoto(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateLostReportPhotoMutationResult = NonNullable<Awaited<ReturnType<typeof updateLostReportPhoto>>>
    export type UpdateLostReportPhotoMutationBody = UpdateLostReportPhotoBody
    export type UpdateLostReportPhotoMutationError = ErrorType<unknown>

    export const useUpdateLostReportPhoto = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLostReportPhoto>>, TError,{id: string;data: UpdateLostReportPhotoBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateLostReportPhoto>>,
        TError,
        {id: string;data: UpdateLostReportPhotoBody},
        TContext
      > => {

      const mutationOptions = getUpdateLostReportPhotoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAllLostReports = (
    params?: GetAllLostReportsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<LostReportResponse[]>(
      {url: `/api/lost-items`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetAllLostReportsQueryKey = (params?: GetAllLostReportsParams,) => {
    return [
    `/api/lost-items`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllLostReportsQueryOptions = <TData = Awaited<ReturnType<typeof getAllLostReports>>, TError = ErrorType<unknown>>(params?: GetAllLostReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllLostReportsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllLostReports>>> = ({ signal }) => getAllLostReports(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAllLostReportsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllLostReports>>>
export type GetAllLostReportsQueryError = ErrorType<unknown>


export function useGetAllLostReports<TData = Awaited<ReturnType<typeof getAllLostReports>>, TError = ErrorType<unknown>>(
 params: undefined |  GetAllLostReportsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllLostReports>>,
          TError,
          Awaited<ReturnType<typeof getAllLostReports>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllLostReports<TData = Awaited<ReturnType<typeof getAllLostReports>>, TError = ErrorType<unknown>>(
 params?: GetAllLostReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllLostReports>>,
          TError,
          Awaited<ReturnType<typeof getAllLostReports>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllLostReports<TData = Awaited<ReturnType<typeof getAllLostReports>>, TError = ErrorType<unknown>>(
 params?: GetAllLostReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAllLostReports<TData = Awaited<ReturnType<typeof getAllLostReports>>, TError = ErrorType<unknown>>(
 params?: GetAllLostReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLostReports>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAllLostReportsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const createLostReport = (
    createLostReportRequest: CreateLostReportRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<LostReportResponse>(
      {url: `/api/lost-items`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createLostReportRequest, signal
    },
      );
    }
  


export const getCreateLostReportMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLostReport>>, TError,{data: CreateLostReportRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createLostReport>>, TError,{data: CreateLostReportRequest}, TContext> => {

const mutationKey = ['createLostReport'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createLostReport>>, {data: CreateLostReportRequest}> = (props) => {
          const {data} = props ?? {};

          return  createLostReport(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateLostReportMutationResult = NonNullable<Awaited<ReturnType<typeof createLostReport>>>
    export type CreateLostReportMutationBody = CreateLostReportRequest
    export type CreateLostReportMutationError = ErrorType<unknown>

    export const useCreateLostReport = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLostReport>>, TError,{data: CreateLostReportRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createLostReport>>,
        TError,
        {data: CreateLostReportRequest},
        TContext
      > => {

      const mutationOptions = getCreateLostReportMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getLostReportPhotoUrl = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PhotoUrlResponse>(
      {url: `/api/lost-items/${id}/photo-url`, method: 'GET', signal
    },
      );
    }
  



export const getGetLostReportPhotoUrlQueryKey = (id?: string,) => {
    return [
    `/api/lost-items/${id}/photo-url`
    ] as const;
    }

    
export const getGetLostReportPhotoUrlQueryOptions = <TData = Awaited<ReturnType<typeof getLostReportPhotoUrl>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhotoUrl>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLostReportPhotoUrlQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLostReportPhotoUrl>>> = ({ signal }) => getLostReportPhotoUrl(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhotoUrl>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetLostReportPhotoUrlQueryResult = NonNullable<Awaited<ReturnType<typeof getLostReportPhotoUrl>>>
export type GetLostReportPhotoUrlQueryError = ErrorType<unknown>


export function useGetLostReportPhotoUrl<TData = Awaited<ReturnType<typeof getLostReportPhotoUrl>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhotoUrl>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportPhotoUrl>>,
          TError,
          Awaited<ReturnType<typeof getLostReportPhotoUrl>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportPhotoUrl<TData = Awaited<ReturnType<typeof getLostReportPhotoUrl>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhotoUrl>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportPhotoUrl>>,
          TError,
          Awaited<ReturnType<typeof getLostReportPhotoUrl>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportPhotoUrl<TData = Awaited<ReturnType<typeof getLostReportPhotoUrl>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhotoUrl>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetLostReportPhotoUrl<TData = Awaited<ReturnType<typeof getLostReportPhotoUrl>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportPhotoUrl>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetLostReportPhotoUrlQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getLostReportHistogram = (
    params?: GetLostReportHistogramParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<HistogramResponse>(
      {url: `/api/lost-items/histogram`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetLostReportHistogramQueryKey = (params?: GetLostReportHistogramParams,) => {
    return [
    `/api/lost-items/histogram`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetLostReportHistogramQueryOptions = <TData = Awaited<ReturnType<typeof getLostReportHistogram>>, TError = ErrorType<unknown>>(params?: GetLostReportHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLostReportHistogramQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLostReportHistogram>>> = ({ signal }) => getLostReportHistogram(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetLostReportHistogramQueryResult = NonNullable<Awaited<ReturnType<typeof getLostReportHistogram>>>
export type GetLostReportHistogramQueryError = ErrorType<unknown>


export function useGetLostReportHistogram<TData = Awaited<ReturnType<typeof getLostReportHistogram>>, TError = ErrorType<unknown>>(
 params: undefined |  GetLostReportHistogramParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportHistogram>>,
          TError,
          Awaited<ReturnType<typeof getLostReportHistogram>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportHistogram<TData = Awaited<ReturnType<typeof getLostReportHistogram>>, TError = ErrorType<unknown>>(
 params?: GetLostReportHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLostReportHistogram>>,
          TError,
          Awaited<ReturnType<typeof getLostReportHistogram>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetLostReportHistogram<TData = Awaited<ReturnType<typeof getLostReportHistogram>>, TError = ErrorType<unknown>>(
 params?: GetLostReportHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetLostReportHistogram<TData = Awaited<ReturnType<typeof getLostReportHistogram>>, TError = ErrorType<unknown>>(
 params?: GetLostReportHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLostReportHistogram>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetLostReportHistogramQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const countLostReports = (
    params?: CountLostReportsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CountResponse>(
      {url: `/api/lost-items/count`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getCountLostReportsQueryKey = (params?: CountLostReportsParams,) => {
    return [
    `/api/lost-items/count`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getCountLostReportsQueryOptions = <TData = Awaited<ReturnType<typeof countLostReports>>, TError = ErrorType<unknown>>(params?: CountLostReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countLostReports>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCountLostReportsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof countLostReports>>> = ({ signal }) => countLostReports(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof countLostReports>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type CountLostReportsQueryResult = NonNullable<Awaited<ReturnType<typeof countLostReports>>>
export type CountLostReportsQueryError = ErrorType<unknown>


export function useCountLostReports<TData = Awaited<ReturnType<typeof countLostReports>>, TError = ErrorType<unknown>>(
 params: undefined |  CountLostReportsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof countLostReports>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof countLostReports>>,
          TError,
          Awaited<ReturnType<typeof countLostReports>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useCountLostReports<TData = Awaited<ReturnType<typeof countLostReports>>, TError = ErrorType<unknown>>(
 params?: CountLostReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countLostReports>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof countLostReports>>,
          TError,
          Awaited<ReturnType<typeof countLostReports>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useCountLostReports<TData = Awaited<ReturnType<typeof countLostReports>>, TError = ErrorType<unknown>>(
 params?: CountLostReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countLostReports>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useCountLostReports<TData = Awaited<ReturnType<typeof countLostReports>>, TError = ErrorType<unknown>>(
 params?: CountLostReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countLostReports>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getCountLostReportsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




