/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CountFoundItemsStatus } from './countFoundItemsStatus';

export type CountFoundItemsParams = {
status?: CountFoundItemsStatus;
venueId?: string;
};
