/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CreateFoundItemRequest } from './createFoundItemRequest';

export type CreateFoundItemBody = {
  request: CreateFoundItemRequest;
  photo: Blob;
};
