/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CreateFoundItemRequest {
  /**
   * @minLength 0
   * @maxLength 2000
   */
  intakeText?: string;
  foundAt: string;
  venueId: string;
  reporterId: string;
}
