/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ItemAttributesDto } from './itemAttributesDto';

export interface CreateFoundItemRequest {
  photoKey?: string;
  description?: string;
  foundAt: string;
  locationHint?: string;
  venueId: string;
  reporterId: string;
  attributes?: ItemAttributesDto;
}
