/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetAllFoundItemsStatus = typeof GetAllFoundItemsStatus[keyof typeof GetAllFoundItemsStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAllFoundItemsStatus = {
  STORED: 'STORED',
  RESERVED: 'RESERVED',
  RETURNED: 'RETURNED',
  DISPOSED: 'DISPOSED',
} as const;
