/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { GetAllFoundItemsStatus } from './getAllFoundItemsStatus';

export type GetAllFoundItemsParams = {
status?: GetAllFoundItemsStatus;
};
