/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { GetFoundItemHistogramStatus } from './getFoundItemHistogramStatus';

export type GetFoundItemHistogramParams = {
status?: GetFoundItemHistogramStatus;
venueId?: string;
};
