/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UpdateFoundItemRequestStatus } from './updateFoundItemRequestStatus';
import type { ItemAttributesDto } from './itemAttributesDto';

export interface UpdateFoundItemRequest {
  intakeText?: string;
  foundAt: string;
  location?: string;
  status: UpdateFoundItemRequestStatus;
  venueId: string;
  reporterId: string;
  attributes?: ItemAttributesDto;
}
