/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateFoundItemRequest,
  FoundItemResponse,
  UpdateFoundItemRequest
} from '.././model';

import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType } from '../../mutator/custom-instance';




export const getFoundItemById = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<FoundItemResponse>(
      {url: `/api/found-items/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetFoundItemByIdQueryKey = (id?: string,) => {
    return [
    `/api/found-items/${id}`
    ] as const;
    }

    
export const getGetFoundItemByIdQueryOptions = <TData = Awaited<ReturnType<typeof getFoundItemById>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFoundItemById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFoundItemByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFoundItemById>>> = ({ signal }) => getFoundItemById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFoundItemById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetFoundItemByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getFoundItemById>>>
export type GetFoundItemByIdQueryError = ErrorType<unknown>


export function useGetFoundItemById<TData = Awaited<ReturnType<typeof getFoundItemById>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFoundItemById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFoundItemById>>,
          TError,
          Awaited<ReturnType<typeof getFoundItemById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetFoundItemById<TData = Awaited<ReturnType<typeof getFoundItemById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFoundItemById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFoundItemById>>,
          TError,
          Awaited<ReturnType<typeof getFoundItemById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetFoundItemById<TData = Awaited<ReturnType<typeof getFoundItemById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFoundItemById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetFoundItemById<TData = Awaited<ReturnType<typeof getFoundItemById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFoundItemById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetFoundItemByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateFoundItem = (
    id: string,
    updateFoundItemRequest: UpdateFoundItemRequest,
 ) => {
      
      
      return customInstance<FoundItemResponse>(
      {url: `/api/found-items/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateFoundItemRequest
    },
      );
    }
  


export const getUpdateFoundItemMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFoundItem>>, TError,{id: string;data: UpdateFoundItemRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateFoundItem>>, TError,{id: string;data: UpdateFoundItemRequest}, TContext> => {

const mutationKey = ['updateFoundItem'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateFoundItem>>, {id: string;data: UpdateFoundItemRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateFoundItem(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateFoundItemMutationResult = NonNullable<Awaited<ReturnType<typeof updateFoundItem>>>
    export type UpdateFoundItemMutationBody = UpdateFoundItemRequest
    export type UpdateFoundItemMutationError = ErrorType<unknown>

    export const useUpdateFoundItem = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFoundItem>>, TError,{id: string;data: UpdateFoundItemRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateFoundItem>>,
        TError,
        {id: string;data: UpdateFoundItemRequest},
        TContext
      > => {

      const mutationOptions = getUpdateFoundItemMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAllFoundItems = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<FoundItemResponse[]>(
      {url: `/api/found-items`, method: 'GET', signal
    },
      );
    }
  



export const getGetAllFoundItemsQueryKey = () => {
    return [
    `/api/found-items`
    ] as const;
    }

    
export const getGetAllFoundItemsQueryOptions = <TData = Awaited<ReturnType<typeof getAllFoundItems>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllFoundItems>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllFoundItemsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllFoundItems>>> = ({ signal }) => getAllFoundItems(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllFoundItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAllFoundItemsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllFoundItems>>>
export type GetAllFoundItemsQueryError = ErrorType<unknown>


export function useGetAllFoundItems<TData = Awaited<ReturnType<typeof getAllFoundItems>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllFoundItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllFoundItems>>,
          TError,
          Awaited<ReturnType<typeof getAllFoundItems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllFoundItems<TData = Awaited<ReturnType<typeof getAllFoundItems>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllFoundItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllFoundItems>>,
          TError,
          Awaited<ReturnType<typeof getAllFoundItems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllFoundItems<TData = Awaited<ReturnType<typeof getAllFoundItems>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllFoundItems>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAllFoundItems<TData = Awaited<ReturnType<typeof getAllFoundItems>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllFoundItems>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAllFoundItemsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const createFoundItem = (
    createFoundItemRequest: CreateFoundItemRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<FoundItemResponse>(
      {url: `/api/found-items`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createFoundItemRequest, signal
    },
      );
    }
  


export const getCreateFoundItemMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFoundItem>>, TError,{data: CreateFoundItemRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createFoundItem>>, TError,{data: CreateFoundItemRequest}, TContext> => {

const mutationKey = ['createFoundItem'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createFoundItem>>, {data: CreateFoundItemRequest}> = (props) => {
          const {data} = props ?? {};

          return  createFoundItem(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateFoundItemMutationResult = NonNullable<Awaited<ReturnType<typeof createFoundItem>>>
    export type CreateFoundItemMutationBody = CreateFoundItemRequest
    export type CreateFoundItemMutationError = ErrorType<unknown>

    export const useCreateFoundItem = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFoundItem>>, TError,{data: CreateFoundItemRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createFoundItem>>,
        TError,
        {data: CreateFoundItemRequest},
        TContext
      > => {

      const mutationOptions = getCreateFoundItemMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    