/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CountFoundItemsParams,
  CountResponse,
  CreateFoundItemRequest,
  FoundItemResponse,
  GetAllFoundItemsParams,
  GetFoundItemHistogramParams,
  HistogramResponse,
  UpdateFoundItemRequest
} from '.././model';

import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType } from '../../mutator/custom-instance';

export type CreateFoundItemMultipartBody = {
  request: CreateFoundItemRequest;
  photo: Blob;
};




export const getFoundItemById = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<FoundItemResponse>(
      {url: `/api/found-items/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetFoundItemByIdQueryKey = (id?: string,) => {
    return [
    `/api/found-items/${id}`
    ] as const;
    }

    
export const getGetFoundItemByIdQueryOptions = <TData = Awaited<ReturnType<typeof getFoundItemById>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFoundItemById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFoundItemByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFoundItemById>>> = ({ signal }) => getFoundItemById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFoundItemById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetFoundItemByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getFoundItemById>>>
export type GetFoundItemByIdQueryError = ErrorType<unknown>


export function useGetFoundItemById<TData = Awaited<ReturnType<typeof getFoundItemById>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFoundItemById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFoundItemById>>,
          TError,
          Awaited<ReturnType<typeof getFoundItemById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetFoundItemById<TData = Awaited<ReturnType<typeof getFoundItemById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFoundItemById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFoundItemById>>,
          TError,
          Awaited<ReturnType<typeof getFoundItemById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetFoundItemById<TData = Awaited<ReturnType<typeof getFoundItemById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFoundItemById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetFoundItemById<TData = Awaited<ReturnType<typeof getFoundItemById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFoundItemById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetFoundItemByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateFoundItem = (
    id: string,
    updateFoundItemRequest: UpdateFoundItemRequest,
 ) => {
      
      
      return customInstance<FoundItemResponse>(
      {url: `/api/found-items/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateFoundItemRequest
    },
      );
    }
  


export const getUpdateFoundItemMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFoundItem>>, TError,{id: string;data: UpdateFoundItemRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateFoundItem>>, TError,{id: string;data: UpdateFoundItemRequest}, TContext> => {

const mutationKey = ['updateFoundItem'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateFoundItem>>, {id: string;data: UpdateFoundItemRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateFoundItem(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateFoundItemMutationResult = NonNullable<Awaited<ReturnType<typeof updateFoundItem>>>
    export type UpdateFoundItemMutationBody = UpdateFoundItemRequest
    export type UpdateFoundItemMutationError = ErrorType<unknown>

    export const useUpdateFoundItem = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFoundItem>>, TError,{id: string;data: UpdateFoundItemRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateFoundItem>>,
        TError,
        {id: string;data: UpdateFoundItemRequest},
        TContext
      > => {

      const mutationOptions = getUpdateFoundItemMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteFoundItem = (
    id: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/found-items/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteFoundItemMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFoundItem>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteFoundItem>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteFoundItem'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteFoundItem>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteFoundItem(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteFoundItemMutationResult = NonNullable<Awaited<ReturnType<typeof deleteFoundItem>>>
    
    export type DeleteFoundItemMutationError = ErrorType<unknown>

    export const useDeleteFoundItem = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFoundItem>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteFoundItem>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteFoundItemMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAllFoundItems = (
    params?: GetAllFoundItemsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<FoundItemResponse[]>(
      {url: `/api/found-items`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetAllFoundItemsQueryKey = (params?: GetAllFoundItemsParams,) => {
    return [
    `/api/found-items`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllFoundItemsQueryOptions = <TData = Awaited<ReturnType<typeof getAllFoundItems>>, TError = ErrorType<unknown>>(params?: GetAllFoundItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllFoundItems>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllFoundItemsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllFoundItems>>> = ({ signal }) => getAllFoundItems(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllFoundItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAllFoundItemsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllFoundItems>>>
export type GetAllFoundItemsQueryError = ErrorType<unknown>


export function useGetAllFoundItems<TData = Awaited<ReturnType<typeof getAllFoundItems>>, TError = ErrorType<unknown>>(
 params: undefined |  GetAllFoundItemsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllFoundItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllFoundItems>>,
          TError,
          Awaited<ReturnType<typeof getAllFoundItems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllFoundItems<TData = Awaited<ReturnType<typeof getAllFoundItems>>, TError = ErrorType<unknown>>(
 params?: GetAllFoundItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllFoundItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllFoundItems>>,
          TError,
          Awaited<ReturnType<typeof getAllFoundItems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllFoundItems<TData = Awaited<ReturnType<typeof getAllFoundItems>>, TError = ErrorType<unknown>>(
 params?: GetAllFoundItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllFoundItems>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAllFoundItems<TData = Awaited<ReturnType<typeof getAllFoundItems>>, TError = ErrorType<unknown>>(
 params?: GetAllFoundItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllFoundItems>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAllFoundItemsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const createFoundItem = (
    createFoundItemMultipartBody: CreateFoundItemMultipartBody,
 signal?: AbortSignal
) => {
      const formData = new FormData();
      formData.append(
        'request',
        new Blob([JSON.stringify(createFoundItemMultipartBody.request)], { type: 'application/json' })
      );
      formData.append('photo', createFoundItemMultipartBody.photo);
      
      return customInstance<FoundItemResponse>(
      {url: `/api/found-items`, method: 'POST',
      data: formData, signal
    },
      );
    }
  


export const getCreateFoundItemMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFoundItem>>, TError,{data: CreateFoundItemMultipartBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createFoundItem>>, TError,{data: CreateFoundItemMultipartBody}, TContext> => {

const mutationKey = ['createFoundItem'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createFoundItem>>, {data: CreateFoundItemMultipartBody}> = (props) => {
          const {data} = props ?? {};

          return  createFoundItem(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateFoundItemMutationResult = NonNullable<Awaited<ReturnType<typeof createFoundItem>>>
    export type CreateFoundItemMutationBody = CreateFoundItemMultipartBody
    export type CreateFoundItemMutationError = ErrorType<unknown>

    export const useCreateFoundItem = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFoundItem>>, TError,{data: CreateFoundItemMultipartBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createFoundItem>>,
        TError,
        {data: CreateFoundItemMultipartBody},
        TContext
      > => {

      const mutationOptions = getCreateFoundItemMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getFoundItemHistogram = (
    params?: GetFoundItemHistogramParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<HistogramResponse>(
      {url: `/api/found-items/histogram`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetFoundItemHistogramQueryKey = (params?: GetFoundItemHistogramParams,) => {
    return [
    `/api/found-items/histogram`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetFoundItemHistogramQueryOptions = <TData = Awaited<ReturnType<typeof getFoundItemHistogram>>, TError = ErrorType<unknown>>(params?: GetFoundItemHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFoundItemHistogram>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFoundItemHistogramQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFoundItemHistogram>>> = ({ signal }) => getFoundItemHistogram(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFoundItemHistogram>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetFoundItemHistogramQueryResult = NonNullable<Awaited<ReturnType<typeof getFoundItemHistogram>>>
export type GetFoundItemHistogramQueryError = ErrorType<unknown>


export function useGetFoundItemHistogram<TData = Awaited<ReturnType<typeof getFoundItemHistogram>>, TError = ErrorType<unknown>>(
 params: undefined |  GetFoundItemHistogramParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFoundItemHistogram>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFoundItemHistogram>>,
          TError,
          Awaited<ReturnType<typeof getFoundItemHistogram>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetFoundItemHistogram<TData = Awaited<ReturnType<typeof getFoundItemHistogram>>, TError = ErrorType<unknown>>(
 params?: GetFoundItemHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFoundItemHistogram>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFoundItemHistogram>>,
          TError,
          Awaited<ReturnType<typeof getFoundItemHistogram>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetFoundItemHistogram<TData = Awaited<ReturnType<typeof getFoundItemHistogram>>, TError = ErrorType<unknown>>(
 params?: GetFoundItemHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFoundItemHistogram>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetFoundItemHistogram<TData = Awaited<ReturnType<typeof getFoundItemHistogram>>, TError = ErrorType<unknown>>(
 params?: GetFoundItemHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFoundItemHistogram>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetFoundItemHistogramQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const countFoundItems = (
    params?: CountFoundItemsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CountResponse>(
      {url: `/api/found-items/count`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getCountFoundItemsQueryKey = (params?: CountFoundItemsParams,) => {
    return [
    `/api/found-items/count`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getCountFoundItemsQueryOptions = <TData = Awaited<ReturnType<typeof countFoundItems>>, TError = ErrorType<unknown>>(params?: CountFoundItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countFoundItems>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCountFoundItemsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof countFoundItems>>> = ({ signal }) => countFoundItems(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof countFoundItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type CountFoundItemsQueryResult = NonNullable<Awaited<ReturnType<typeof countFoundItems>>>
export type CountFoundItemsQueryError = ErrorType<unknown>


export function useCountFoundItems<TData = Awaited<ReturnType<typeof countFoundItems>>, TError = ErrorType<unknown>>(
 params: undefined |  CountFoundItemsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof countFoundItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof countFoundItems>>,
          TError,
          Awaited<ReturnType<typeof countFoundItems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useCountFoundItems<TData = Awaited<ReturnType<typeof countFoundItems>>, TError = ErrorType<unknown>>(
 params?: CountFoundItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countFoundItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof countFoundItems>>,
          TError,
          Awaited<ReturnType<typeof countFoundItems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useCountFoundItems<TData = Awaited<ReturnType<typeof countFoundItems>>, TError = ErrorType<unknown>>(
 params?: CountFoundItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countFoundItems>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useCountFoundItems<TData = Awaited<ReturnType<typeof countFoundItems>>, TError = ErrorType<unknown>>(
 params?: CountFoundItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countFoundItems>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getCountFoundItemsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




