/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CreatePickupScheduleRequestRecurrenceType } from './createPickupScheduleRequestRecurrenceType';
import type { CreatePickupScheduleRequestDayOfWeek } from './createPickupScheduleRequestDayOfWeek';

export interface CreatePickupScheduleRequest {
  recurrenceType?: CreatePickupScheduleRequestRecurrenceType;
  startDate: string;
  endDate?: string;
  dayOfWeek?: CreatePickupScheduleRequestDayOfWeek;
  startTime: string;
  endTime: string;
  /** @minimum 1 */
  slotLengthInMinutes?: number;
  venueId?: string;
}
