/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PickupScheduleResponseRecurrenceType = typeof PickupScheduleResponseRecurrenceType[keyof typeof PickupScheduleResponseRecurrenceType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PickupScheduleResponseRecurrenceType = {
  ONCE: 'ONCE',
  WEEKLY: 'WEEKLY',
} as const;
