/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UpdatePickupScheduleRequestRecurrenceType = typeof UpdatePickupScheduleRequestRecurrenceType[keyof typeof UpdatePickupScheduleRequestRecurrenceType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdatePickupScheduleRequestRecurrenceType = {
  ONCE: 'ONCE',
  WEEKLY: 'WEEKLY',
} as const;
