{{- if .Values.tempo.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-data
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "foundflow.labels" . | nindent 4 }}
    app.kubernetes.io/name: tempo
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.global.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.tempo.storageSize }}
{{- end }}
