/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CountLostReports1Status } from './countLostReports1Status';

export type CountLostReports1Params = {
status?: CountLostReports1Status;
venueId?: string;
};
