/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { GetAllLostReports1Status } from './getAllLostReports1Status';

export type GetAllLostReports1Params = {
status?: GetAllLostReports1Status;
};
