/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetAllLostReports1Status = typeof GetAllLostReports1Status[keyof typeof GetAllLostReports1Status];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAllLostReports1Status = {
  OPEN: 'OPEN',
  MATCHED: 'MATCHED',
  CLOSED: 'CLOSED',
  COLLECTED: 'COLLECTED',
} as const;
