/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { LostReportResponseStatus } from './lostReportResponseStatus';
import type { ItemAttributesDto } from './itemAttributesDto';

export interface LostReportResponse {
  id?: string;
  photoKey?: string;
  description?: string;
  lostAt?: string;
  location?: string;
  status?: LostReportResponseStatus;
  venueId?: string;
  contactEmail?: string;
  attributes?: ItemAttributesDto;
}
