/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UpdateLostReportRequestStatus = typeof UpdateLostReportRequestStatus[keyof typeof UpdateLostReportRequestStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateLostReportRequestStatus = {
  OPEN: 'OPEN',
  MATCHED: 'MATCHED',
  CLOSED: 'CLOSED',
  COLLECTED: 'COLLECTED',
} as const;
