/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CountMatchesParams,
  CountResponse,
  CreateMatchRequest,
  CreatePublicMatchLinkRequest,
  GetAllMatchesParams,
  GetMatchHistogramParams,
  HistogramResponse,
  MatchResponse,
  PublicFoundItemResponse,
  PublicMatchLinkResponse,
  UpdateMatchRequest
} from '.././model';

import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType } from '../../mutator/custom-instance';




export const getMatchById = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<MatchResponse>(
      {url: `/api/matches/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetMatchByIdQueryKey = (id?: string,) => {
    return [
    `/api/matches/${id}`
    ] as const;
    }

    
export const getGetMatchByIdQueryOptions = <TData = Awaited<ReturnType<typeof getMatchById>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatchById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMatchByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMatchById>>> = ({ signal }) => getMatchById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMatchById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetMatchByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getMatchById>>>
export type GetMatchByIdQueryError = ErrorType<unknown>


export function useGetMatchById<TData = Awaited<ReturnType<typeof getMatchById>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatchById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMatchById>>,
          TError,
          Awaited<ReturnType<typeof getMatchById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetMatchById<TData = Awaited<ReturnType<typeof getMatchById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatchById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMatchById>>,
          TError,
          Awaited<ReturnType<typeof getMatchById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetMatchById<TData = Awaited<ReturnType<typeof getMatchById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatchById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetMatchById<TData = Awaited<ReturnType<typeof getMatchById>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatchById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetMatchByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateMatch = (
    id: string,
    updateMatchRequest: UpdateMatchRequest,
 ) => {
      
      
      return customInstance<MatchResponse>(
      {url: `/api/matches/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateMatchRequest
    },
      );
    }
  


export const getUpdateMatchMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMatch>>, TError,{id: string;data: UpdateMatchRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateMatch>>, TError,{id: string;data: UpdateMatchRequest}, TContext> => {

const mutationKey = ['updateMatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMatch>>, {id: string;data: UpdateMatchRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateMatch(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateMatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateMatch>>>
    export type UpdateMatchMutationBody = UpdateMatchRequest
    export type UpdateMatchMutationError = ErrorType<unknown>

    export const useUpdateMatch = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMatch>>, TError,{id: string;data: UpdateMatchRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMatch>>,
        TError,
        {id: string;data: UpdateMatchRequest},
        TContext
      > => {

      const mutationOptions = getUpdateMatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const rejectPublicMatch = (
    token: string,
 ) => {
      
      
      return customInstance<MatchResponse>(
      {url: `/api/matches/public/match-links/${token}/reject`, method: 'PUT'
    },
      );
    }
  


export const getRejectPublicMatchMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rejectPublicMatch>>, TError,{token: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof rejectPublicMatch>>, TError,{token: string}, TContext> => {

const mutationKey = ['rejectPublicMatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rejectPublicMatch>>, {token: string}> = (props) => {
          const {token} = props ?? {};

          return  rejectPublicMatch(token,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RejectPublicMatchMutationResult = NonNullable<Awaited<ReturnType<typeof rejectPublicMatch>>>
    
    export type RejectPublicMatchMutationError = ErrorType<unknown>

    export const useRejectPublicMatch = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rejectPublicMatch>>, TError,{token: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof rejectPublicMatch>>,
        TError,
        {token: string},
        TContext
      > => {

      const mutationOptions = getRejectPublicMatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const confirmPublicMatch = (
    token: string,
 ) => {
      
      
      return customInstance<MatchResponse>(
      {url: `/api/matches/public/match-links/${token}/confirm`, method: 'PUT'
    },
      );
    }
  


export const getConfirmPublicMatchMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmPublicMatch>>, TError,{token: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof confirmPublicMatch>>, TError,{token: string}, TContext> => {

const mutationKey = ['confirmPublicMatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof confirmPublicMatch>>, {token: string}> = (props) => {
          const {token} = props ?? {};

          return  confirmPublicMatch(token,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ConfirmPublicMatchMutationResult = NonNullable<Awaited<ReturnType<typeof confirmPublicMatch>>>
    
    export type ConfirmPublicMatchMutationError = ErrorType<unknown>

    export const useConfirmPublicMatch = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmPublicMatch>>, TError,{token: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof confirmPublicMatch>>,
        TError,
        {token: string},
        TContext
      > => {

      const mutationOptions = getConfirmPublicMatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAllMatches = (
    params?: GetAllMatchesParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<MatchResponse[]>(
      {url: `/api/matches`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetAllMatchesQueryKey = (params?: GetAllMatchesParams,) => {
    return [
    `/api/matches`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllMatchesQueryOptions = <TData = Awaited<ReturnType<typeof getAllMatches>>, TError = ErrorType<unknown>>(params?: GetAllMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllMatches>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllMatchesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllMatches>>> = ({ signal }) => getAllMatches(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllMatches>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAllMatchesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllMatches>>>
export type GetAllMatchesQueryError = ErrorType<unknown>


export function useGetAllMatches<TData = Awaited<ReturnType<typeof getAllMatches>>, TError = ErrorType<unknown>>(
 params: undefined |  GetAllMatchesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllMatches>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllMatches>>,
          TError,
          Awaited<ReturnType<typeof getAllMatches>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllMatches<TData = Awaited<ReturnType<typeof getAllMatches>>, TError = ErrorType<unknown>>(
 params?: GetAllMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllMatches>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllMatches>>,
          TError,
          Awaited<ReturnType<typeof getAllMatches>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllMatches<TData = Awaited<ReturnType<typeof getAllMatches>>, TError = ErrorType<unknown>>(
 params?: GetAllMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllMatches>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetAllMatches<TData = Awaited<ReturnType<typeof getAllMatches>>, TError = ErrorType<unknown>>(
 params?: GetAllMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllMatches>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAllMatchesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const createMatch = (
    createMatchRequest: CreateMatchRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<MatchResponse>(
      {url: `/api/matches`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createMatchRequest, signal
    },
      );
    }
  


export const getCreateMatchMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMatch>>, TError,{data: CreateMatchRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createMatch>>, TError,{data: CreateMatchRequest}, TContext> => {

const mutationKey = ['createMatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMatch>>, {data: CreateMatchRequest}> = (props) => {
          const {data} = props ?? {};

          return  createMatch(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateMatchMutationResult = NonNullable<Awaited<ReturnType<typeof createMatch>>>
    export type CreateMatchMutationBody = CreateMatchRequest
    export type CreateMatchMutationError = ErrorType<unknown>

    export const useCreateMatch = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMatch>>, TError,{data: CreateMatchRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createMatch>>,
        TError,
        {data: CreateMatchRequest},
        TContext
      > => {

      const mutationOptions = getCreateMatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const createPublicMatchLink = (
    id: string,
    createPublicMatchLinkRequest: CreatePublicMatchLinkRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PublicMatchLinkResponse>(
      {url: `/api/matches/${id}/public-link`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPublicMatchLinkRequest, signal
    },
      );
    }
  


export const getCreatePublicMatchLinkMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPublicMatchLink>>, TError,{id: string;data: CreatePublicMatchLinkRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createPublicMatchLink>>, TError,{id: string;data: CreatePublicMatchLinkRequest}, TContext> => {

const mutationKey = ['createPublicMatchLink'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPublicMatchLink>>, {id: string;data: CreatePublicMatchLinkRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  createPublicMatchLink(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePublicMatchLinkMutationResult = NonNullable<Awaited<ReturnType<typeof createPublicMatchLink>>>
    export type CreatePublicMatchLinkMutationBody = CreatePublicMatchLinkRequest
    export type CreatePublicMatchLinkMutationError = ErrorType<unknown>

    export const useCreatePublicMatchLink = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPublicMatchLink>>, TError,{id: string;data: CreatePublicMatchLinkRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPublicMatchLink>>,
        TError,
        {id: string;data: CreatePublicMatchLinkRequest},
        TContext
      > => {

      const mutationOptions = getCreatePublicMatchLinkMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getPublicMatch = (
    token: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<MatchResponse>(
      {url: `/api/matches/public/${token}`, method: 'GET', signal
    },
      );
    }
  



export const getGetPublicMatchQueryKey = (token?: string,) => {
    return [
    `/api/matches/public/${token}`
    ] as const;
    }

    
export const getGetPublicMatchQueryOptions = <TData = Awaited<ReturnType<typeof getPublicMatch>>, TError = ErrorType<unknown>>(token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicMatch>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPublicMatchQueryKey(token);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPublicMatch>>> = ({ signal }) => getPublicMatch(token, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(token), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPublicMatch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetPublicMatchQueryResult = NonNullable<Awaited<ReturnType<typeof getPublicMatch>>>
export type GetPublicMatchQueryError = ErrorType<unknown>


export function useGetPublicMatch<TData = Awaited<ReturnType<typeof getPublicMatch>>, TError = ErrorType<unknown>>(
 token: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicMatch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPublicMatch>>,
          TError,
          Awaited<ReturnType<typeof getPublicMatch>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPublicMatch<TData = Awaited<ReturnType<typeof getPublicMatch>>, TError = ErrorType<unknown>>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicMatch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPublicMatch>>,
          TError,
          Awaited<ReturnType<typeof getPublicMatch>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPublicMatch<TData = Awaited<ReturnType<typeof getPublicMatch>>, TError = ErrorType<unknown>>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicMatch>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetPublicMatch<TData = Awaited<ReturnType<typeof getPublicMatch>>, TError = ErrorType<unknown>>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicMatch>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetPublicMatchQueryOptions(token,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getPublicFoundItem = (
    token: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PublicFoundItemResponse>(
      {url: `/api/matches/public/${token}/found-item`, method: 'GET', signal
    },
      );
    }
  



export const getGetPublicFoundItemQueryKey = (token?: string,) => {
    return [
    `/api/matches/public/${token}/found-item`
    ] as const;
    }

    
export const getGetPublicFoundItemQueryOptions = <TData = Awaited<ReturnType<typeof getPublicFoundItem>>, TError = ErrorType<unknown>>(token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicFoundItem>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPublicFoundItemQueryKey(token);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPublicFoundItem>>> = ({ signal }) => getPublicFoundItem(token, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(token), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPublicFoundItem>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetPublicFoundItemQueryResult = NonNullable<Awaited<ReturnType<typeof getPublicFoundItem>>>
export type GetPublicFoundItemQueryError = ErrorType<unknown>


export function useGetPublicFoundItem<TData = Awaited<ReturnType<typeof getPublicFoundItem>>, TError = ErrorType<unknown>>(
 token: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicFoundItem>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPublicFoundItem>>,
          TError,
          Awaited<ReturnType<typeof getPublicFoundItem>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPublicFoundItem<TData = Awaited<ReturnType<typeof getPublicFoundItem>>, TError = ErrorType<unknown>>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicFoundItem>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPublicFoundItem>>,
          TError,
          Awaited<ReturnType<typeof getPublicFoundItem>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPublicFoundItem<TData = Awaited<ReturnType<typeof getPublicFoundItem>>, TError = ErrorType<unknown>>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicFoundItem>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetPublicFoundItem<TData = Awaited<ReturnType<typeof getPublicFoundItem>>, TError = ErrorType<unknown>>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicFoundItem>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetPublicFoundItemQueryOptions(token,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getMatchHistogram = (
    params?: GetMatchHistogramParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<HistogramResponse>(
      {url: `/api/matches/histogram`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetMatchHistogramQueryKey = (params?: GetMatchHistogramParams,) => {
    return [
    `/api/matches/histogram`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetMatchHistogramQueryOptions = <TData = Awaited<ReturnType<typeof getMatchHistogram>>, TError = ErrorType<unknown>>(params?: GetMatchHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatchHistogram>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMatchHistogramQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMatchHistogram>>> = ({ signal }) => getMatchHistogram(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMatchHistogram>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetMatchHistogramQueryResult = NonNullable<Awaited<ReturnType<typeof getMatchHistogram>>>
export type GetMatchHistogramQueryError = ErrorType<unknown>


export function useGetMatchHistogram<TData = Awaited<ReturnType<typeof getMatchHistogram>>, TError = ErrorType<unknown>>(
 params: undefined |  GetMatchHistogramParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatchHistogram>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMatchHistogram>>,
          TError,
          Awaited<ReturnType<typeof getMatchHistogram>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetMatchHistogram<TData = Awaited<ReturnType<typeof getMatchHistogram>>, TError = ErrorType<unknown>>(
 params?: GetMatchHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatchHistogram>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMatchHistogram>>,
          TError,
          Awaited<ReturnType<typeof getMatchHistogram>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetMatchHistogram<TData = Awaited<ReturnType<typeof getMatchHistogram>>, TError = ErrorType<unknown>>(
 params?: GetMatchHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatchHistogram>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetMatchHistogram<TData = Awaited<ReturnType<typeof getMatchHistogram>>, TError = ErrorType<unknown>>(
 params?: GetMatchHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatchHistogram>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetMatchHistogramQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const countMatches = (
    params?: CountMatchesParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CountResponse>(
      {url: `/api/matches/count`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getCountMatchesQueryKey = (params?: CountMatchesParams,) => {
    return [
    `/api/matches/count`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getCountMatchesQueryOptions = <TData = Awaited<ReturnType<typeof countMatches>>, TError = ErrorType<unknown>>(params?: CountMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countMatches>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCountMatchesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof countMatches>>> = ({ signal }) => countMatches(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof countMatches>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type CountMatchesQueryResult = NonNullable<Awaited<ReturnType<typeof countMatches>>>
export type CountMatchesQueryError = ErrorType<unknown>


export function useCountMatches<TData = Awaited<ReturnType<typeof countMatches>>, TError = ErrorType<unknown>>(
 params: undefined |  CountMatchesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof countMatches>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof countMatches>>,
          TError,
          Awaited<ReturnType<typeof countMatches>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useCountMatches<TData = Awaited<ReturnType<typeof countMatches>>, TError = ErrorType<unknown>>(
 params?: CountMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countMatches>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof countMatches>>,
          TError,
          Awaited<ReturnType<typeof countMatches>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useCountMatches<TData = Awaited<ReturnType<typeof countMatches>>, TError = ErrorType<unknown>>(
 params?: CountMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countMatches>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useCountMatches<TData = Awaited<ReturnType<typeof countMatches>>, TError = ErrorType<unknown>>(
 params?: CountMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countMatches>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getCountMatchesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




