/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CountMatchesParams,
  CountResponse,
  GetMatchHistogramParams,
  HistogramResponse
} from '.././model';

import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType } from '../../mutator/custom-instance';




export const getMatchHistogram = (
    params?: GetMatchHistogramParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<HistogramResponse>(
      {url: `/api/matches/histogram`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetMatchHistogramQueryKey = (params?: GetMatchHistogramParams,) => {
    return [
    `/api/matches/histogram`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetMatchHistogramQueryOptions = <TData = Awaited<ReturnType<typeof getMatchHistogram>>, TError = ErrorType<unknown>>(params?: GetMatchHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatchHistogram>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMatchHistogramQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMatchHistogram>>> = ({ signal }) => getMatchHistogram(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMatchHistogram>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetMatchHistogramQueryResult = NonNullable<Awaited<ReturnType<typeof getMatchHistogram>>>
export type GetMatchHistogramQueryError = ErrorType<unknown>


export function useGetMatchHistogram<TData = Awaited<ReturnType<typeof getMatchHistogram>>, TError = ErrorType<unknown>>(
 params: undefined |  GetMatchHistogramParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatchHistogram>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMatchHistogram>>,
          TError,
          Awaited<ReturnType<typeof getMatchHistogram>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetMatchHistogram<TData = Awaited<ReturnType<typeof getMatchHistogram>>, TError = ErrorType<unknown>>(
 params?: GetMatchHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatchHistogram>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMatchHistogram>>,
          TError,
          Awaited<ReturnType<typeof getMatchHistogram>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetMatchHistogram<TData = Awaited<ReturnType<typeof getMatchHistogram>>, TError = ErrorType<unknown>>(
 params?: GetMatchHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatchHistogram>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetMatchHistogram<TData = Awaited<ReturnType<typeof getMatchHistogram>>, TError = ErrorType<unknown>>(
 params?: GetMatchHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMatchHistogram>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetMatchHistogramQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const countMatches = (
    params?: CountMatchesParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CountResponse>(
      {url: `/api/matches/count`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getCountMatchesQueryKey = (params?: CountMatchesParams,) => {
    return [
    `/api/matches/count`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getCountMatchesQueryOptions = <TData = Awaited<ReturnType<typeof countMatches>>, TError = ErrorType<unknown>>(params?: CountMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countMatches>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCountMatchesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof countMatches>>> = ({ signal }) => countMatches(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof countMatches>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type CountMatchesQueryResult = NonNullable<Awaited<ReturnType<typeof countMatches>>>
export type CountMatchesQueryError = ErrorType<unknown>


export function useCountMatches<TData = Awaited<ReturnType<typeof countMatches>>, TError = ErrorType<unknown>>(
 params: undefined |  CountMatchesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof countMatches>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof countMatches>>,
          TError,
          Awaited<ReturnType<typeof countMatches>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useCountMatches<TData = Awaited<ReturnType<typeof countMatches>>, TError = ErrorType<unknown>>(
 params?: CountMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countMatches>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof countMatches>>,
          TError,
          Awaited<ReturnType<typeof countMatches>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useCountMatches<TData = Awaited<ReturnType<typeof countMatches>>, TError = ErrorType<unknown>>(
 params?: CountMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countMatches>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useCountMatches<TData = Awaited<ReturnType<typeof countMatches>>, TError = ErrorType<unknown>>(
 params?: CountMatchesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countMatches>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getCountMatchesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




